### PR TITLE
Fix for #225 "Code fix for RM3 breaks when queries contain special characters"

### PR DESCRIPTION
**Pull request by lintool**
wip, not ready for merging.

We need to do regression on collections first...

### CODE REVIEW

**Comment by Peilin-Yang** [comment]
So you have regression tests all done?

**Comment by lintool** [comment]
@Peilin-Yang Regression tests have completed. Everything checks out and we can now run RM3 on all collections. Ready for review and merge.

**Comment by Peilin-Yang** [comment]
@lintool You are _going to_ run RM3 for all collections? I thought all the results were verified...
So what is your plan? First merge it and run RM3, or after all the results are validated?

**Comment by lintool** [comment]
I've already run all RM3 results and verified that it works. Updated results reflected in this PR.

**Comment by Peilin-Yang** [comment]
Oh, okay.
As I do not see any changes for Microblog collections, is that b/c numbers are not changed? Or if you haven't done this part probably I can help to test as there is no indexing process involved.

**Comment by lintool** [comment]
Nope, numbers haven't changed.

**Comment by Peilin-Yang** [comment]
Perfect! Thanks!

**Pull request merged**
