### PR TITLE
Patch for #366: Separate FileSegment interface from AbstractFileSegment impl

### PR DESCRIPTION
**Pull request by lintool**
Patch for issue #366 
Also cleaned up Javadoc. All docs in collection package no read consistently.

### CODE REVIEW

**Comment by lintool** [comment]
@Peilin-Yang yes I agree it's a bit confusing but not that bad...

+ A user is unlikely going to be using more than one collection at once, so I think it's okay that all the collection inner classes have the same name.
+ From the perspective of the Indexer, it only needs to care about the interface.

I don't like `FileSegmentImpl` because then we should have `DocumentImpl` to be consistent, which is kinda ugly.

How's this?

+ `AbstractFileSegment` -> `BaseFileSegment` per your suggestion.
+ `Foo.FileSegment` -> `Foo.Segment`: since they are under the collection class, it's clear that they are file segments. In principle we could have `MemorySegment` or even `StreamSegment` later?

So `Segment` will always refer to concrete impl in the context of various collections, and `FileSegment` will unambiguously refer to the abstraction?

**Comment by Peilin-Yang** [comment]
I feel it should be the other way around - `Segment` as the name of the interface and `FileSegment` inside each collection. `MemorySegment` and `StreamSegment` are other types of `Segment`.

**Comment by lintool** [comment]
Okay, `Segment` interface, `BaseFileSegment`, and `FileSegment` inner classes?

**Comment by Peilin-Yang** [comment]
LGTM

**Pull request merged**
