### PR TITLE
Rm3Reranker: Construct query manually instead of using Lucene's Query…

### LINKED ISSUE #429: Refactor RM3 to avoid use of query parser
Currently, the RM3 implementation constructs a text query, and then calls the Lucene parser to parse it, see: https://github.com/castorini/Anserini/blob/master/src/main/java/io/anserini/rerank/lib/Rm3Reranker.java#L84

This is a bit janky - we want to programmatically construct the query and avoid using the query parser.

### PR DESCRIPTION
**Pull request by r-clancy**
…Parser.

Fixes #429

### CODE REVIEW

**Comment by r-clancy** [comment]
@lintool I've confirmed with `core17` that that the experimental results are the same as before.

**Comment by lintool** [comment]
Can you run on our standard battery of regression tests?

```
nohup python src/main/python/run_regression.py --collection disk12 >& log.disk12 &
nohup python src/main/python/run_regression.py --collection robust04 >& log.robust04 &
nohup python src/main/python/run_regression.py --collection robust05 >& log.robust05 &
nohup python src/main/python/run_regression.py --collection core17 >& log.core17 &

nohup python src/main/python/run_regression.py --collection car17 >& log.car17 &

nohup python src/main/python/run_regression.py --collection mb11 >& log.mb11 &
nohup python src/main/python/run_regression.py --collection mb13 >& log.mb13 &

nohup python src/main/python/run_regression.py --collection wt10g >& log.wt10g &
nohup python src/main/python/run_regression.py --collection gov2 >& log.gov2 &
nohup python src/main/python/run_regression.py --collection cw09b >& log.cw09b &
nohup python src/main/python/run_regression.py --collection cw12b13 >& log.cw12b13 &
nohup python src/main/python/run_regression.py --collection cw12 >& log.cw12 &
```

This is just a matter of cut and paste and wait... see if your new code trips a corner case.

**Comment by r-clancy** [comment]
@lintool I'm not getting the expected results, I'll have to take a deeper look at it.

**Comment by r-clancy** [comment]
@lintool 

I've taken a deep look into the results - it appears that the old query parser method had an error when handling small (or large, I suppose) floating point numbers. 

When the query was parsed, a space was added between the number and "E" - this meant that the letter "E" was part of the query. See the image below for a diff between the old parser generated query (left) and new manually constructed BoostQuery (right).

mb13_1

I've submitted another PR with the updated values for the regression tests - I'm running the regressions once more as a sanity check and will follow-up once they've finished.

**Comment by lintool** [comment]
Great!

@Peilin-Yang I told you that using the query parser was janky and bug-prone! :)

@r-clancy One more set of regressions - just copy and paste and verify:
https://github.com/castorini/Anserini/blob/master/docs/experiments-jdiq2018.md

**Comment by r-clancy** [comment]
@lintool All the regressions look good, no failures.

**Pull request merged**
