### PR TITLE
Add to onboarding repro logs

### PR DESCRIPTION
**Pull request by vincent-4**
Worked on Maven 3.9.9 + JDK 21

Banana odyssey?

Let me know if I could get access to the slack channel.

Thank you!

### CODE REVIEW

**Review by lintool — APPROVED** [review]

**Comment by lintool** [comment]
@vincent-4 have you done the pyserini onboarding?

**Comment by vincent-4** [comment]
Yes @lintool - https://github.com/castorini/pyserini/pull/2032

**Comment by lintool** [comment]
@vincent-4 email me please.

**Comment by vincent-4** [comment]
Emailed you a few days ago!

**Pull request merged**
