### PR TITLE
rearrange search bar

### PR DESCRIPTION
**Pull request by nicoella**
added change for search bar form on search enter

### CODE REVIEW

**Comment by lintool** [comment]
hey @16BitNarwhal can you please take a look here?

**Comment by lintool** [comment]
@nicoella maybe add a screenshot of the new UI to this thread?

**Comment by nicoella** [comment]
[](url)

https://github.com/user-attachments/assets/834ec8ab-5e74-48b1-9822-fac163cb66e9

Here's a demo video!

**Review by 16BitNarwhal — APPROVED** [review]
looks good!

**Pull request merged**
