### PR TITLE
Replication for BM25 Baselines on MS MARCO Passage Retrieval and MS MARCO Doc Retrieval Tasks

### PR DESCRIPTION
**Pull request by TianchengY**
Environment:
OS: MacOS Mojave 10.14.4 
Java: openjdk version "1.8.0_152-release"
Python: 3.6.8

Issues for BM25 Baselines on MS MARCO Passage Retrieval:

- The first command in this [section](https://github.com/castorini/anserini/blob/master/docs/experiments-msmarco-passage.md#retrieving-and-evaluating-the-dev-set) should have a path prefix of `collections/`. I've changed it in my PR

- The second command in the same section above will return an error 
```
tenseisBookpuro:msmarco yangtiancheng$ python ./src/main/python/msmarco/retrieve.py --hits 1000 --threads 1  --index indexes/msmarco-passage/lucene-index-msmarco --qid_queries collections/msmarco-passage/queries.dev.small.tsv  --output runs/run.msmarco-passage.dev.small.tsv
Initializing BM25, setting k1=0.82 and b=0.68
Traceback (most recent call last):
  File "./src/main/python/msmarco/retrieve.py", line 58, in <module>
    hits = searcher.search(query.encode('utf8'), int(args.hits))
  File "/anaconda3/lib/python3.6/site-packages/pyserini/search/pysearch.py", line 99, in search
    return self.object.search(JString(q.encode('utf8')), k)
AttributeError: 'bytes' object has no attribute 'encode'
```

No issues found for BM25 Baselines on MS MARCO Doc Retrieval Task, everything runs well.

### CODE REVIEW

**Comment by lintool** [comment]
Please recheck with my branch: https://github.com/castorini/anserini/pull/1238

**Comment by TianchengY** [comment]
> Please recheck with my branch: #1238

I've updated, and the error
```
AttributeError: 'bytes' object has no attribute 'encode'
```
still exists.

**Comment by lintool** [comment]
From your "files changed" in this PR, it doesn't seem like you've pulled the latest master?

**Comment by TianchengY** [comment]
> From your "files changed" in this PR, it doesn't seem like you've pulled the latest master?

I've updated to this commit [`2947a16`](https://github.com/castorini/anserini/commit/2947a1622efae35637b83e321aba8e6fccd43489)), 
is it the latest one?

**Comment by TianchengY** [comment]
> From your "files changed" in this PR, it doesn't seem like you've pulled the latest master?

I pulled from the remote [repository](https://github.com/castorini/anserini.git) and then force push the updates to my own forked [repository](https://github.com/TianchengY/anserini.git)

**Comment by TianchengY** [comment]
> From your "files changed" in this PR, it doesn't seem like you've pulled the latest master?

Sorry the issue of `AttributeError` was resolved, when I was testing I run the command in the directory of the old version of the castorini (I have the habit to backup the previous step) by mistake.

**Pull request merged**
