### PR TITLE
give more information in raw() of WARC indexes 

### PR DESCRIPTION
**Pull request by MXueguang**
It was returning the WARC content only.

By issue https://github.com/castorini/anserini/issues/1259, since other info such as URL might be useful, it is better to keep them in raw().
Now it will return a json dict with `Date`, `ID`, `URL`, `Document`

### CODE REVIEW

**Comment by lintool** [comment]
hey @shaneding you're pretty familiar with Anserini at this point, can you take a look?

@MXueguang What I'm trying to decide is whether this is a one-off ugly hack, or if this is generally a good idea, to just start stuffing fields in `raw()` output as a JSON... An alternative, for example, would be for `raw()` to just return the entire WARC crawl record - which obviously has all this stuff in it, right? And let the client parse out whatever they want...

I'm worried that if we start "structuring" the "raw" document, we start down the path of endless document parsing whenever someone want some new field...

cc @ronakice thoughts?

**Comment by shaneding** [comment]
I just took a quick look, why can't we just add `URL`, `date`, and etc as fields in the lucene index? Why do we need to organize it for raw? @lintool

**Comment by lintool** [comment]
@shaneding *slaps forehead* e.g., like a custom generator? e.g., https://github.com/castorini/anserini/blob/master/src/main/java/io/anserini/index/generator/Iso19115Generator.java

@MXueguang I think that's a clean solution?

**Comment by shaneding** [comment]
Exactly, I think thats a more general solution and making them fields just make searching a lot more robust imho @lintool.

**Comment by MXueguang** [comment]
@lintool @shaneding Yeah, custom generator is indeed a much better solution.
Thanks for your suggestions. I'll update it asap

**Comment by MXueguang** [comment]
now the url (or date) are expect to retrieval via:
`hits[0].lucene_document.get("url")`

**Comment by lintool** [comment]
Sorry, I'm missing the broader context: why did `readNextRecord` get removed? and whats this integer offset?
Can we add a simple test case?

**Comment by MXueguang** [comment]
Sorry I reverted something back.

I noticed there might be a bug for the `readNextRecord`. Some of the raws of WARC doc seems missing the last character. I thought it was only for CommonCrawl but I just notice it happened to ClueWeb as well. I need to further investigate this to make sure if it is actually a "bug". It it does, i think i should fix that in a new PR. (It shouldn't influence any current indexing anyway because the last char of `raw` never kept in `contents`)

**Comment by lintool** [comment]
Can we easily add a test to somewhere in https://github.com/castorini/anserini/tree/master/src/test/java/io/anserini/collection ?

**Comment by MXueguang** [comment]
Added test cases for all collections that using `WarcBaseDocument`

**Review by lintool — APPROVED** [review]

**Pull request merged**
