### PR TITLE
Replication for elastrini and solrini

### PR DESCRIPTION
**Pull request by shaneding**
- General: Had to use ./bin/qbuild.sh rather than the mvn clean package appassembler:assemble given in the docs (not sure if its just me or a general issue)

Elastrini and Solrini:
- MS MARCO Passage: No issues, but retrieval takes really long, maybe create shorter file just for replication, like in the original MS MARCO passage replication?

### CODE REVIEW

**Comment by lintool** [comment]
> * General: Had to use ./bin/qbuild.sh rather than the mvn clean package appassembler:assemble given in the docs (not sure if its just me or a general issue)

What's your env setup? OS, Java version, etc. What errors are you getting?

**Comment by shaneding** [comment]
Environment
OS: macOS 10.15 (Catalina)
Java: 14.0.1
Python: 3.7.6

Error:
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.12.4:test (default-test) on project anserini: Execution default-test of goal org.apache.maven.plugins:maven-surefire-plugin:2.12.4:test failed: The forked VM terminated without saying properly goodbye. VM crash or System.exit called ? -> [Help 1]

**Comment by lintool** [comment]
@shaneding 

> Java: 14.0.1

That's the issue... I think this is a known issue - https://github.com/castorini/anserini/issues/1198

**Comment by shaneding** [comment]
Okay, so should ./qbuild.sh be used in place of "mvn clean package appassembler:assemble" for now?

**Comment by lintool** [comment]
@shaneding I think the cleaner solution would be for you to downgrade to Java 11 so that you can stay in sync with the project... so you won't run into other JVM compat issues down the road...

**Pull request merged**
