### PR TITLE
Reproduced same results

### PR DESCRIPTION
**Pull request by Nebu0528**
Recreated results; Windows 11 Pro; OS build: 22631.3296

### CODE REVIEW

**Comment by lintool** [comment]
Please add more details about your repro, e.g., OS, config, etc.

Also, continue along the onboarding path until you reach the end of the exercises, and then we'll take a look all at once.

**Comment by Nebu0528** [comment]
Hello Professor, I am building anserini using Maven 3.3.3, I am running into errors, I have tried 3.9.6 and it is giving the same issue. Do you have a specific version of Maven you'd recommend using?

**Comment by Nebu0528** [comment]
image

Apologies if this is not the place to show my errors, but I changed my java version to 21 and maven to 3.9+ from the updated readme and it is not able to connect to the link above.

**Comment by lintool** [comment]
Having heard no follow-up, closing issue. Please reopen if you've made progress.

**Pull request closed without merging**
