### PR TITLE
Add Entries to Reproduction Log for Anserini BM25 Baselines for MS MARCO Passage Ranking

### PR DESCRIPTION
**Pull request by Edward-J-Xu**
**OS & Hardware**: Student Environment (Ubuntu2204)

**Result**: I was able to replicate the MS MARCO Tour (i.e. download & extra the data, data munging and analyze qrels files) on my machine with the above settings. Outputs are the same as listed in the "start-here" document. 

**Hiccups**: On student env we need to install our own jdk, else it won't build

**Fix**(what I did):
1. Download openjdk version 11 or higher in tar.gz
2. SCP it to the student env and extract at your place
3. Update JAVA_HOME in .bashrc

### CODE REVIEW

**Comment by lintool** [comment]
Queuing up for merge.

> Hiccups: On student env we need to install our own jdk, else it won't build

Can you provide brief instructions?

**Comment by lintool** [comment]
hi @Edward-J-Xu - one PR ahead of you got merged in and creates conflict now. Can you please sort out and then I'll merge.

**Comment by Edward-J-Xu** [comment]
fixed :) thanks so much @lintool

**Comment by lintool** [comment]
Sorry, just noticed:

```
https://github.com/castorini/anserini/commit/adcdc27fa2810885b3551b74f2d3dd4bfca73f9f
```

This is an invalid commit: "This commit does not belong to any branch on this repository, and may belong to a fork outside of the repository."

You want to point to something that's on main Anserini trunk, the closest point where you did your repo, before you forked.

**Review by lintool — APPROVED** [review]

**Pull request merged**
