### PR TITLE
Replicated MS MARCO passage ranking, doc ranking, and doc2query (MS MARCO + CAR) experiments

### PR DESCRIPTION
**Pull request by kelvin-jiang**
Environment
OS: Ubuntu 18.04.1 LTS
Java: openjdk 11.0.7 2020-04-14
Python: 3.6.9

MS MARCO passage ranking experiment:
* Fixed a command where one of the file paths was missing `collections/` prefix

doc2query experiment:
* Updated all of the file paths to follow the new `collections/` and `indexes/` repo structure
* Got a different word count for `wc collections/msmarco-passage/pred-test_topk10.txt`: line count and character count were still the same, the MD5 checksum was the same, and the final eval results were the same, so I updated the `wc` output

I also updated the username (it's me) in a replication entry for robust04.

### CODE REVIEW

**Comment by lintool** [comment]
Did you rename your GitHub account names? I think the release notes need to be updated as well? https://github.com/castorini/anserini/blob/master/docs/release-notes/release-notes-v0.9.3.md

Can you grep through and fix those instances?

**Comment by kelvin-jiang** [comment]
Yeah, I did. I could fix those instances in the release notes, but it's a bit problematic cause my old commits are still attributed to my old username in Github (not sure why Github does that), so the tool that collects the repo's contributors will still pick up my old username in the future.

**Comment by lintool** [comment]
That's fine, I can do the mapping by hand in the future... but whatever you prefer...

**Comment by lintool** [comment]
Please recheck with my branch: https://github.com/castorini/anserini/pull/1238

**Comment by kelvin-jiang** [comment]
Reran the MS MARCO passage ranking experiment on updated master and #1222 seems to be resolved now.

**Comment by kelvin-jiang** [comment]
Both files should be checked in already?

**Comment by lintool** [comment]
oops, didn't notice all the way at the end...

**Pull request merged**
