### PR TITLE
Upgrade Anserini to Lucene (and Solr) 9.0.0

### PR DESCRIPTION
**Pull request by tteofili**
This PR upgrades Lucene and Solr dependencies to versions 9.0.0.

### CODE REVIEW

**Comment by lintool** [comment]
hey @tteofili - I'm getting an exception during indexing:

```
Exception in thread "main" java.lang.NoClassDefFoundError: org/apache/lucene/util/fst/Builder
	at org.apache.lucene.analysis.miscellaneous.StemmerOverrideFilter$Builder.build(StemmerOverrideFilter.java:206)
	at org.apache.lucene.analysis.nl.DutchAnalyzer.<init>(DutchAnalyzer.java:134)
	at org.apache.lucene.analysis.nl.DutchAnalyzer.<init>(DutchAnalyzer.java:107)
	at io.anserini.index.IndexCollection.run(IndexCollection.java:755)
	at io.anserini.index.IndexCollection.main(IndexCollection.java:978)
Caused by: java.lang.ClassNotFoundException: org.apache.lucene.util.fst.Builder
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:583)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	... 5 more
```

Is there something obvious that I'm missing?

**Comment by tteofili** [comment]
that depends on https://lucene.apache.org/core/9_0_0/MIGRATE.html#oalutilfstbuilder-is-renamed-fstcompiler-with-fluent-style-builder-lucene-9089
if the HC4 code uses it, `fst.Builder` references should. be moved to `fst.FSTCompiler `.

**Comment by lintool** [comment]
> that depends on https://lucene.apache.org/core/9_0_0/MIGRATE.html#oalutilfstbuilder-is-renamed-fstcompiler-with-fluent-style-builder-lucene-9089 if the HC4 code uses it, `fst.Builder` references should. be moved to `fst.FSTCompiler `.

Ah, awesome! I'll try that.

@tteofili just to give you a head's up - the current plan is to cut a final release artifact using Lucene 8.X, and then merge this in and move to Lucene 9.

**Comment by tteofili** [comment]
> @tteofili just to give you a head's up - the current plan is to cut a final release artifact using Lucene 8.X, and then merge this in and move to Lucene 9.

ok, that's great !

**Review by lintool — APPROVED** [review]

**Pull request merged**
