### PR TITLE
Ingesting CORD-19 into Solr and ES

### PR DESCRIPTION
**Pull request by yxzhu16**
OS: macOS Sierra 10.12.6
Java: 11.0.8
Python: 3.8.3
Ruby: 2.7.1

Encountered an exception while running ES indexing for Abstract, Full-Text, and paragraph. Stack trace:

`ERROR [pool-2-thread-1] index.IndexCollection$ESIndexerThread (IndexCollection.java:575) - Error sending bulk requests to Elasticsearch
org.elasticsearch.ElasticsearchStatusException: Unable to parse response body
	at org.elasticsearch.client.RestHighLevelClient.parseResponseException(RestHighLevelClient.java:1686) ~[elasticsearch-rest-high-level-client-7.0.0.jar:7.0.0]
	at org.elasticsearch.client.RestHighLevelClient.internalPerformRequest(RestHighLevelClient.java:1446) ~[elasticsearch-rest-high-level-client-7.0.0.jar:7.0.0]
	at org.elasticsearch.client.RestHighLevelClient.performRequest(RestHighLevelClient.java:1403) ~[elasticsearch-rest-high-level-client-7.0.0.jar:7.0.0]
	at org.elasticsearch.client.RestHighLevelClient.performRequestAndParseEntity(RestHighLevelClient.java:1373) ~[elasticsearch-rest-high-level-client-7.0.0.jar:7.0.0]
	at org.elasticsearch.client.RestHighLevelClient.bulk(RestHighLevelClient.java:477) ~[elasticsearch-rest-high-level-client-7.0.0.jar:7.0.0]
	at io.anserini.index.IndexCollection$ESIndexerThread.sendBulkRequest(IndexCollection.java:572) [anserini-0.9.5-SNAPSHOT.jar:?]
	at io.anserini.index.IndexCollection$ESIndexerThread.run(IndexCollection.java:518) [anserini-0.9.5-SNAPSHOT.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
	at java.lang.Thread.run(Thread.java:834) [?:?]
	Suppressed: java.lang.IllegalStateException: Elasticsearch didn't return the [Content-Type] header, unable to parse response body`

The indexing seemed to continue after this exception popped up, and I was able to make some queries in Kibana at the end. It seems like @shaneding encountered the same issue here: https://github.com/castorini/anserini/pull/1223

Screen Shot 2020-07-17 at 6 49 14 PM

### CODE REVIEW

**Comment by lintool** [comment]
hi @yxzhu16 - can you track down this exception in a bit more detail? Would be good to isolate it, to for example, a specific document...

**Comment by yxzhu16** [comment]
Hi @lintool . I looked into the code and was able to log the file that caused the exception. It seems like it's [metadata.csv](https://github.com/castorini/anserini/blob/master/src/test/resources/sample_docs/cord19/sample1/metadata.csv).
Screen Shot 2020-07-20 at 12 28 05 PM

**Comment by lintool** [comment]
@yxzhu16 yes, `metadata.csv` contains the entire corpus... are we able to isolate to a specific document? I suspect it's documents that are too long... but let's see if we can confirm.

**Comment by lintool** [comment]
With #1333 merged, you can go back to this now!

**Comment by yxzhu16** [comment]
Hi @lintool , yes I've tested the indexing of abstract, paragraph, and full-text with the latest merges, they all went through and no exceptions were thrown. So this can also be merged now.

**Pull request merged**
