### PR TITLE
Fixes #441: test failure

### LINKED ISSUE #441: Failed tests: WashingtonPostDocumentTest.test
The test in subject fails when doing mvn clean install appassembler:assemle

Running io.anserini.collection.WashingtonPostDocumentTest
NOTE: reproduce with: ant test  -Dtestcase=WashingtonPostDocumentTest -Dtests.method=test -Dtests.seed=1F9ADA48760EEFFA -Dtests.locale=da-DK -Dtests.timezone=Australia/Melbourne -Dtests.asserts=true -Dtests.file.encoding=ANSI_X3.4-1968
NOTE: leaving temporary files on disk at: /tmp/io.anserini.collection.WashingtonPostDocumentTest_1F9ADA48760EEFFA-001
NOTE: test params are: codec=Asserting(Lucene62): {}, docValues:{}, maxPointsInLeafNode=1872, maxMBSortInHeap=6.402142198457144, sim=ClassicSimilarity, locale=da-DK, timezone=Australia/Melbourne
NOTE: Linux 4.4.0-128-generic amd64/Oracle Corporation 1.8.0_181 (64-bit)/cpus=16,threads=1,free=238009520,total=430440448
NOTE: All tests run in this JVM: [TweetEndToEndTest, TrecEndToEndTest, IndexerTest, SdmQueryTest, SCQFeatureExtractorTest, BM25FeatureExtractorTest, SCSFeatureExtractorTest, UnigramFeaturesTest, LoadFeatureExtractorFromFileTest, TFIDFFeatureExtractorTest, DocSizeFeatureExtractorTest, TermFrequencyFeatureExtractorTest, BigramFeaturesTest, PMIFeatureExtractorTest, FeatureExtractorChainFromJsonTest, AvgIDFFeatureExtractorTest, ICTFFeatureExtractorTest, DocumentTest, TrecwebDocumentTest, JsonDocumentArrayTest, WikipediaArticleTest, JsonDocumentObjectTest, WashingtonPostDocumentTest]
Tests run: 2, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 0.063 sec <<< FAILURE! - in io.anserini.collection.WashingtonPostDocumentTest
test(io.anserini.collection.WashingtonPostDocumentTest)  Time elapsed: 0.03 sec  <<< FAILURE!
org.junit.ComparisonFailure: expected:<...ght can ease jet lag[???]s effects before and...> but was:<...ght can ease jet lag[?]s effects before and...>
	at __randomizedtesting.SeedInfo.seed([1F9ADA48760EEFFA:97CEE592D8F28202]:0)
	at org.junit.Assert.assertEquals(Assert.java:115)
	at org.junit.Assert.assertEquals(Assert.java:144)
	at io.anserini.collection.WashingtonPostDocumentTest.test(WashingtonPostDocumentTest.java:83)

### PR DESCRIPTION
**Pull request by lintool**
Fixes #441 - @catenamatteo can you verify this works?

### CODE REVIEW

**Comment by lintool** [comment]
@catenamatteo nudge?

**Comment by catenamatteo** [comment]
Hi Jimmy, sorry for the late reply. The fix doesn't work.

**Comment by lintool** [comment]
@catenamatteo Any suggestions? I can't replicate the bug so I can't test...

**Comment by lintool** [comment]
Awesome. I'll close this PR as a failed fix then.

Would you mind sending the PR to fix this issue per above? Easy enough for me to do, but we'd like to recognize your contributions, as in:
https://github.com/castorini/Anserini/blob/master/docs/release-notes/release-notes-v0.2.0.md

(This is auto generated based on the commits.)

**Comment by lintool** [comment]
Fixed by #454

**Pull request closed without merging**
