### PR TITLE
Fixed broken MB13 regression

### PR DESCRIPTION
**Pull request by lintool**
See issue #409 documenting MB13 regression failure. Source can be traced back to
6b19d373634d510e8ac5f5b26b1a3d5c321926e4

In MB13 there are duplicate documents: optimize flag forces segment merge to clean this up,
yielding different index stats.

Rerunning regression now as final confirmation.

### CODE REVIEW

**Comment by lintool** [comment]
My hypothesis is that "update" is the culprit... not sure how it's implemented behind the scenes, but - say, if update is actually an insertion + deletion, then deletion leaves a tombstone that would be reclaimed on optimize, which is a compaction, right?

**Comment by Peilin-Yang** [comment]
I dunno... Just curious that why the issue wasn't there.. 
Apparently, for collection such as MB13 that has duplicated documents we will not be able to get the actual indexed documents until the index is completely built.

**Comment by lintool** [comment]
Regression failed... It appears that the number of docs are non-deterministic! What??

```
$ target/appassembler/bin/IndexUtils -index lucene-index.mb13.pos+docvectors+rawdocs -stats
Index statistics
----------------
documents:             203145916
documents (non-empty): 203143470
unique terms:          -1
total terms:           2099084597
stored fields:
  contents (indexOption: DOCS_AND_FREQS_AND_POSITIONS, hasVectors: true)
  id (indexOption: DOCS, hasVectors: false)
  lang (indexOption: DOCS, hasVectors: false)
  screen_name (indexOption: DOCS, hasVectors: false)
```

**Comment by Peilin-Yang** [comment]
@lintool Is that possible different indexing threads can not see each other's (duplicated) documents? Thus we will have to turn on `-optimize` to finalize?

**Comment by Peilin-Yang** [comment]
Tested with `-optimize` two times and both have passed.
The run files are exactly the same too. 
So it seems that we will have to keep `-optimize` for MB collections.

**Pull request merged**
