### PR TITLE
Reproducing Results for Anserini

### PR DESCRIPTION
**Pull request by Pie31415**
# Development Environment
- Fresh WSL Ubuntu 20.04.4 on Windows 10
- Python 3.8.13
- Java 11.0.13
- Apache Maven 3.8.6

# Results
Able to reproduce results that appear on guide.

### CODE REVIEW

**Comment by lintool** [comment]
@Pie31415 I assumed regressions checked out and all the numbers match?

**Comment by lintool** [comment]
btw, when I navigate to your commit id https://github.com/castorini/anserini/commit/8f3104af21b9e4c369b22d0b9af4bf423680c4c8 , I get:

```
This commit does not belong to any branch on this repository, and may belong to a fork outside of the repository.
```

Please change this to the commit id of the anserini repo that you ran the regressions on?

**Comment by Pie31415** [comment]
> @Pie31415 I assumed regressions checked out and all the numbers match?

Yes, my results matched the ones that appeared on the guide.

**Comment by Pie31415** [comment]
> btw, when I navigate to your commit id [8f3104a](https://github.com/castorini/anserini/commit/8f3104af21b9e4c369b22d0b9af4bf423680c4c8) , I get:
> 
> ```
> This commit does not belong to any branch on this repository, and may belong to a fork outside of the repository.
> ```
> 
> Please change this to the commit id of the anserini repo that you ran the regressions on?

Alright, I fixed the commit id.

**Review by lintool — APPROVED** [review]

**Pull request merged**
