### PR TITLE
STM - Replicate BM25 baselines for MS MARCO Doc and Passage retrieval tasks

### PR DESCRIPTION
**Pull request by stariqmi**
### Environment
**OS**: Ubuntu 18.04.4 LTS
**Java**: openjdk version "11.0.7" 2020-04-14
**Python**: Python 3.6.9

### Issues

- Memory - I had to use an AWS EC2 `t2.2xlarge` instance to replicate the results
- `collections` - I had to also create the `collections` directory
- pyserini - There is no requirements.txt file that mentions `pyserini` so had to install that manually

No issues found for BM25 Baselines on MS MARCO Passage and Doc Retrieval Tasks.

### CODE REVIEW

**Comment by stariqmi** [comment]
@lintool I am not sure about which commit to link to in this.

**Comment by lintool** [comment]
What commit did you use to replicate the results?

**Comment by lintool** [comment]
> `collections` - I had to also create the collections directory

This is a bit odd, we have the `collections/` directory in the repo: https://github.com/castorini/anserini/tree/master/collections

Wonder what's going on...?

**Comment by stariqmi** [comment]
> > `collections` - I had to also create the collections directory
> 
> This is a bit odd, we have the `collections/` directory in the repo: https://github.com/castorini/anserini/tree/master/collections
> 
> Wonder what's going on...?

This was a mistake on my part. I used the incorrect directory initially. I walked through my bash history to replicate and realized that.

**Pull request merged**
