### PR TITLE
make it possible to index/search MSMarco with fw/lexlsh ann

### PR DESCRIPTION
**Pull request by tteofili**
this extends `IndexInvertedDenseVectors` and `SearchInvertedDenseVectors`, InvertedDenseVectorsDocumentGenerator and `InvertedDenseVectorsQueryGenerator` to allow users to index MSMarco using LSH or FW analyzers.
Indexing command example:

```bash
./target/appassembler/bin/IndexInvertedDenseVectors -collection JsonDenseVectorCollection -generator InvertedDenseVectorsDocumentGenerator -threads 1 -index /path/to/fw-msmarco-passage/ -input /path/to/vector-cos-dpr-msmarco-passage -encoding fw 
```
Search command example:
```bash
./target/appassembler/bin/SearchInvertedDenseVectors  -index /path/to/index-cos-dpr-msmarco-passage/ \
 -topics /path/to/vector-cos-dpr-msmarco-passage-dev-query/encoded-query.jsonl \
 -topicreader JsonIntVector \
 -querygenerator InvertedDenseVectorsQueryGenerator \
 -output run.ann-cos-dpr-msmarco-dev.trec \
 -topicfield vector \
 -hits 100 
```

### CODE REVIEW

**Comment by tteofili** [comment]
this is an up to date version of #2059

**Comment by lintool** [comment]
hey @tteofili 
> Submodule [tools](https://github.com/castorini/anserini-tools) updated [75 files](https://github.com/castorini/anserini-tools/compare/80691da60909ef0a123a0643e8af6552d741281e...95fbaf2af75e2b59304ac5702d5479d50f3bd9ef)

I think you want to update submodule to where master now points?

**Comment by tteofili** [comment]
sure, I'll fix that

**Comment by tteofili** [comment]
here're the commands one can use to run inverted dense vectors algo on MSMarco.

For `fw`, run indexing with:
```
cd /path/to/anserini
./target/appassembler/bin/IndexVectors -collection JsonDenseVectorCollection -generator InvertedDenseVectorDocumentGenerator -threads 16 -index ../fw-msmarco-passage/ -input /path/to/vector-cos-dpr-msmarco-passage -encoding fw
```
index size is 9.7G
index time 08h24m39s

run search with:
```
./target/appassembler/bin/ApproximateNearestNeighborSearch -index ../fw-msmarco-passage/  -topics /path/to/vector-cos-dpr-msmarco-passage-dev-query/encoded-query.jsonl  -topicreader JsonIntVector  -output run.fw-cos-dpr-msmarco-dev.trec  -topicfield vector -hits 1000 -encoding fw -threads 16 -threadsPerQuery 16
```
6980 queries processed in 05:23:35 = ~0.36 q/s

run eval with:
```
cd /path/to/pyserini
python -m pyserini.eval.trec_eval -c -mrecip_rank -M 10 msmarco-passage-dev-subset ../anserini/run.fw_cos-dpr-msmarco-dev.trec
```
you get  _MRR@10 = 0.3642_

For `lexlsh`, run indexing with:
```
cd /path/to/anserini
./target/appassembler/bin/IndexVectors -collection JsonDenseVectorCollection -generator InvertedDenseVectorDocumentGenerator -threads 16 -index ../lexlsh-msmarco-passage/ -input /path/to/vector-cos-dpr-msmarco-passage -encoding lexlsh
```
index size is 2.1G
index time 09h01m41s

run search with:
```
./target/appassembler/bin/ApproximateNearestNeighborSearch -index ../lexlsh-msmarco-passage/  -topics /path/to/vector-cos-dpr-msmarco-passage-dev-query/encoded-query.jsonl  -topicreader JsonIntVector  -output run.lexlsh-cos-dpr-msmarco-dev.trec  -topicfield vector -hits 1000 -encoding lexlsh -threads 16 -threadsPerQuery 16
```
6980 queries processed in 00:59:03 = ~1.97 q/s

run eval with:
```
cd /path/to/pyserini
python -m pyserini.eval.trec_eval -c -mrecip_rank -M 10 msmarco-passage-dev-subset ../anserini/run.lexlsh_cos-dpr-msmarco-dev.trec
```
you get _MRR@10 = 0.1363_

**Comment by tteofili** [comment]
in summary these are some results with MSMarco:

|encoding|params|indexing time|index size|qps|MRR@10|
|-------------|-------------|-------------|-------------|-------------|-------------|
|fw|q=60|8h24|9.7GB|0.36|0.3642|
|lexlsh|b=300|9h01m|2.1GB|1.97|0.1363|
|lexlsh|b=500|9h26|3.5GB|0.41|0.3397|

**Review by lintool — APPROVED** [review]
lgtm based on a quick skim.

However, before you merge please make sure you update submodule tool to latest?

**Comment by tteofili** [comment]
it should be good to be merged @lintool

**Pull request merged**
