### PR TITLE
Patch for #254: Refactor readnextrecord in SourceDocument

### PR DESCRIPTION
**Pull request by borislin**
Refactored readNextRecord in SourceDocument and all collections

### CODE REVIEW

**Comment by Peilin-Yang** [comment]
#353 is not part of this PR, right?
Should we consider to incorporate it in this PR?

**Comment by borislin** [comment]
@Peilin-Yang 

#353 is not part of this PR

I think we should do #353 is a separate PR. #352 refactored and implemented a proper iterator for each file segment. In #353, we will iterate through a file segment via the iterator until EOF and submit each document returned by `iter.next()` to the work pool to achieve maximum parallelism.

**Comment by borislin** [comment]
@Peilin-Yang 

Per my conversation with @lintool on Slack, what I've said in my previous comment is incorrect. #353 will build a separate mapper util function using work pool. The simplest demo will be counting number of docs over the entire collection. This util is completely independent of our current pipeline.

So we should not incorporate #353 into this PR. I'll do #353 in a separate PR.

**Comment by lintool** [comment]
@borislin As a sanity check please run regressions over everything except cw12 before merging:

```
nohup python src/main/python/run_regression.py --collection disk12 --index >& log.disk12 &
nohup python src/main/python/run_regression.py --collection robust04 --index >& log.robust04 &
nohup python src/main/python/run_regression.py --collection robust05 --index >& log.robust05 &
nohup python src/main/python/run_regression.py --collection core17 --index >& log.core17 &

nohup python src/main/python/run_regression.py --collection mb11 --index >& log.mb11 &
nohup python src/main/python/run_regression.py --collection mb13 --index >& log.mb13 &

nohup python src/main/python/run_regression.py --collection wt10g --index >& log.wt10g &
nohup python src/main/python/run_regression.py --collection gov2 --index >& log.gov2 &
nohup python src/main/python/run_regression.py --collection cw09b --index >& log.cw09b &
nohup python src/main/python/run_regression.py --collection cw12b13 --index >& log.cw12b13 &
```

These shouldn't take that long... After merging, I'll run the full cw12 regression:

```
nohup python src/main/python/run_regression.py --collection cw12 --index >& log.cw12 &
```

**Pull request merged**
