### PR TITLE
Fix zero norm bug

### PR DESCRIPTION
**Pull request by Victor0118**
@lintool @Peilin-Yang Could you take a quick look at this PR?

The bug detail is in #374 .

### CODE REVIEW

**Comment by lintool** [comment]
@Victor0118 I don’t think this is the right fix... this will impact the quality of the estimated RM. we should actually remove those documents...

**Comment by Victor0118** [comment]
According to the [source code](https://github.com/apache/lucene-solr/blob/master/lucene/analysis/common/src/java/org/apache/lucene/analysis/en/EnglishAnalyzer.java), Englishanalyzer does not remove the word containing special character.

But in RM3 [implementation](https://github.com/castorini/Anserini/blob/master/src/main/java/io/anserini/rerank/lib/Rm3Reranker.java#L191) in Anserini, you remove words contain character not in [a-z0-9]. Is there any special reason to do this?

**Comment by lintool** [comment]
The `[a-z0-9]` throws away terms that are likely to be junk... if we remove that line, then all the RM3 results will change, then we need to verify all the effectiveness numbers, etc. I'd rather not do that...

**Comment by Victor0118** [comment]
Another choice is adding a condition like this:
``` java
if (len(doc) < threshold){
   // do not add doc to the RM3 candidate
}
```

This can also avoid the junk document in Wikipedia corpus. Good?

**Comment by lintool** [comment]
Yes, although that might also change regression results...

Why don't we just throw away all feature vectors with norm of 0?

**Comment by Victor0118** [comment]
Okay. That makes sense!

**Comment by lintool** [comment]
Can you run the regression experiments to make sure everything still works?
https://github.com/castorini/Anserini/blob/master/docs/regression-tuna.md

**Comment by Victor0118** [comment]
OKay!

**Comment by Victor0118** [comment]
```
no segments* file found in MMapDirectory@/tuna1/indexes/lucene-index.aquaint.pos+docvectors+rawdocs
no segments* file found in MMapDirectory@/tuna1/indexes/lucene-index.nyt.pos+docvectors+rawdocs
no segments* file found in MMapDirectory@/tuna1/indexes/lucene-index.tweets2011.pos+docvectors+rawdocs
no segments* file found in MMapDirectory@/tuna1/indexes/lucene-index.tweets2013.pos+docvectors+rawdocs
```
@lintool All regression tests passed except four index files not found above.

**Comment by Victor0118** [comment]
@lintool All regression test passed!

**Comment by lintool** [comment]
@Victor0118 great!
One final thing - can you add a comment that explains why we do that check in the code? Then we'll be good for merging.

**Comment by Victor0118** [comment]
@lintool Done.

**Comment by lintool** [comment]
How about a comment that is more descriptive? Like:

Avoids zero-length feedback documents, which causes division by zero when computing term weights.
Zero-length feedback documents occur (e.g., with CAR17) when a document has only terms that accents (which are indexed, but not selected for feedback).

**Comment by Victor0118** [comment]
@lintool Thanks for your kind suggestion. I have updated the comment.

**Pull request merged**
