### PR TITLE
Add to onboarding reproduction logs

### PR DESCRIPTION
**Pull request by w-y-li**
Hardware:
CPU: AMD EPYC 7713 64-Core Processor
RAM: 1007.69GB

Environment:

Operating System: linux 5.4.0-170-generic
Python Version: Python 3.10.13
Java Version: openjdk 17.0.10

At _Anserini: BM25 Baselines for MS MARCO Passage Ranking_ when do the indexing part got some trouble, maybe you can write more clearly at this place.Best wishes!

### CODE REVIEW

**Comment by lintool** [comment]
Hi @w-y-li thanks for your PR - please fix conflicts?

> At _Anserini: BM25 Baselines for MS MARCO Passage Ranking_ when do the indexing part got some trouble, maybe you can write more clearly at this place.Best wishes!

Also, can you suggest how I might better improve the docs?

**Comment by w-y-li** [comment]
Hi, maybe you can say detaily without just say "using the instructions in ...".
Whatever, this is just my personal opinion, maybe not correct.

**Review by lintool — CHANGES_REQUESTED** [review]
When I go to your URL https://github.com/castorini/anserini/commit/ed3c88158383f51348e63024339e637b69646d05

I get the error: This commit does not belong to any branch on this repository, and may belong to a fork outside of the repository.

Please fix. Commit to refer to a commit on anserini master.

**Comment by lintool** [comment]
https://github.com/castorini/anserini/discussions/2428

**Comment by lintool** [comment]
Having heard no follow-up, closing issue. Please reopen if you've made progress.

**Pull request closed without merging**
