### PR TITLE
Covid Passage Indexing

### LINKED ISSUE #1044: COVID-19 collection: Implement passage indexing
As discussed: an article = ID, TITLE + ABSTRACT (+ P1 + P2 + P3)?...

Decompose into:

+ ID, TITLE + ABSTRACT
+ ID.0001, TITLE + ABSTRACT + P1
+ ID.0002, TITLE + ABSTRACT + P2

### PR DESCRIPTION
**Pull request by nikhilro**
Resolves #1044 and #1045 

Per the issue, a record is decomposed into (id, content, raw):
* ID, TITLE + ABSTRACT, FULL_TEXT_JSON
* ID.0001, TITLE + ABSTRACT + P1, ""
* ID.0002, TITLE + ABSTRACT + P2, ""

Edits to documentation to resolve `xargs` issues and updates to expected number of documents.

In regards to #1048, the CovidCollection's SourceDocument adds `raw` which is ultimately what goes to `raw` for the document. This is the simplest implementation I think

### CODE REVIEW

**Comment by lintool** [comment]
hey @nikhilro I'm thinking (but up for discussion) that the paragraph chopping should be performed in the `Generator`?

That is each `SourceDocument` still presents an independent article, but the `Generator` does the chopping into multiple paragraphs and a Lucene document for each.

**Comment by nikhilro** [comment]
My mental model for `Collection` vs `Generator` is that the collection deals with actual files on the system whereas the generator never has to worry about that. To generator, there is a guarantee that the document data exists and it's job is to convert it to `LuceneDocument`. So, I think it makes more sense to keep it in `CovidCollection`

**Comment by lintool** [comment]
In this design, each `Collection` has arbitrary flexibility in presenting what it thinks its "content" should be. 

In this case, it'd be `CSVRecord(\nJSON_FULL_TEXT)?`. The Generator knows what to do with this in generating Lucene `Documents`.

**Comment by nikhilro** [comment]
> In this design, each Collection has arbitrary flexibility in presenting what it thinks its "content" should be.

confused, the current implementation?

**Comment by lintool** [comment]
> My mental model for `Collection` vs `Generator` is that the collection deals with actual files on the system whereas the generator never has to worry about that. To generator, there is a guarantee that the document data exists and it's job is to convert it to `LuceneDocument`. So, I think it makes more sense to keep it in `CovidCollection`

But what about the case if we want to change the indexing scheme? Let's say later on we find out that paragraph by paragraph isn't that good, and we want to change to, say sliding window of 2 paragraphs?

In your design, you'd need to modify the collection.

And if you want to keep both, you'd need two collections.

**Comment by lintool** [comment]
> > In this design, each Collection has arbitrary flexibility in presenting what it thinks its "content" should be.
> 
> confused, the current implementation?

Yes, that's the implicit contract of the current design, I think.

**Comment by nikhilro** [comment]
> In your design, you'd need to modify the collection.
And if you want to keep both, you'd need two collections.

Yes, that seems reasonable to me. Maybe Collection isn't the best word for it but `Generator` to seems has a simple job. Convert 1 `SourceDocument` to 1 `LuceneDocument`

**Comment by lintool** [comment]
> > In your design, you'd need to modify the collection.
> > And if you want to keep both, you'd need two collections.
> 
> Yes, that seems reasonable to me. Maybe Collection isn't the best word for it but `Generator` to seems has a simple job. Convert 1 `SourceDocument` to 1 `LuceneDocument`

I think I like the contract of Generator as Convert 1 `SourceDocument` to _N_ `LuceneDocument`.

So in my design, you'd have 1 Collection, but multiple generators. E.g.,

+ `CovidFullDocumentGenerator`
+ `CovidParagraphGenerator`
+ `CovidSlidingParagraphWindowGenerator`

**Comment by nikhilro** [comment]
To implement `1 SourceDocument to N LuceneDocument`, there'd be two complications:

* We need to change pieces of our core design. Right now, all a generator does is `createDocument(SourceDocument)` which is expected to return 1 LuceneDocument. Each generator will have to implement some complex iterator logic to support the aforementioned 1:N SourceDocument:LuceneDocument.

* Even if we could change the above, there is an additional complexity on creating those N `LuceneDocument`s in the `Generator`. This will involve JsonNode, CSVParser, BufferedReader etc. having to move to `Generator` in addition to staying in `Collection`.

**Comment by edwinzhng** [comment]
> To implement `1 SourceDocument to N LuceneDocument`, there'd be two complications:
> 
> * We need to change pieces of our core design. Right now, all a generator does is `createDocument(SourceDocument)` which is expected to return 1 LuceneDocument. Each generator will have to implement some complex iterator logic to support the aforementioned 1:N SourceDocument:LuceneDocument.
> * Even if we could change the above, there is an additional complexity on creating those N `LuceneDocument`s in the `Generator`. This will involve JsonNode, CSVParser, BufferedReader etc. having to move to `Generator` in addition to staying in `Collection`.

In that case, we would just need to modify the IndexCollection to support a list of returned documents instead of a single one (and probably modify all existing generators to return a list of size == 1)

https://github.com/castorini/anserini/blob/master/src/main/java/io/anserini/index/IndexCollection.java#L195

**Comment by lintool** [comment]
Okay, I think you've sold me. We'll go with your design.

But let's keep both `CovidCollection` (the old one) and also `CovidParagraphCollection` (new one)? Maybe refactor to inherit from same super class?

**Comment by nikhilro** [comment]
Sounds good!

**Comment by lintool** [comment]
Actually, @nikhilro can we have three versions? (1) title/abstract only, (2) full text, and (3) title/abstract/each paragraph.

Down the road, we probably want to evaluate them...

**Comment by nikhilro** [comment]
and to clarify those three versions

* (1) title/abstract only: `CovidCollection`
  * (id, content, raw)
  * (ROW_NUMBER, TITLE + ABSTRACT, FULL_JSON_TEXT)

* (2) full text: `CovidFullTextCollection`
  * (id, content, raw)
  * (ROW_NUMBER, TITLE + ABSTRACT + FULL_JSON_TEXT, FULL_JSON_TEXT)

* and (3) title/abstract/each paragraph: ``CovidParagraphCollection`
  * (id, content, raw)
  * (ROW_NUMBER, TITLE + ABSTRACT, FULL_JSON_TEXT)
  * (ROW_NUMBER.001, TITLE + ABSTRACT + P1, "")
  * (ROW_NUMBER.002, TITLE + ABSTRACT + P2, "")
  * ....

**Comment by lintool** [comment]
> and to clarify those three versions
> 
> * (1) title/abstract only: `CovidCollection`
>   
>   * (id, content, raw)
>   * (ROW_NUMBER, TITLE + ABSTRACT, FULL_JSON_TEXT)

First bullet is input, and remaining our outputs Lucene docs, right? If so, yes.

**Comment by nikhilro** [comment]
yea, I was mentioning the format in each for the upcoming bullets (id, content, raw) :sweat_smile:. Sounds good, on it.

**Comment by nikhilro** [comment]
Gonna get @edwinzhng 's help to get the inheritance working in Java

**Comment by nikhilro** [comment]
```
sh target/appassembler/bin/IndexCollection \
    -collection CovidCollection -generator CovidGenerator \
    -threads 8 -input "${DATA_DIR}" \
    -index "${DATA_DIR}"/lucene-index-covid \
    -storePositions -storeDocvectors -storeRawDocs -storeTransformedDocs
``` 
works but same with `CovidFullTextCollection` because of inheritance issues that @edwinzhng will fix. Thanks!

**Pull request merged**
