### PR TITLE
Update all regressions for NeuCLIR22

### PR DESCRIPTION
**Pull request by lintool**
@cadurosar Q for you - what do you want to call the SPLADE model?

In terms of initial sanity checking... do the numbers look right to you?

### CODE REVIEW

**Comment by lintool** [comment]
The documentation in readable format: 
+ QT BM25: https://github.com/castorini/anserini/blob/neuclir22-splade/docs/regressions-neuclir22-fa-qt.md#effectiveness
+ QT SPLADE: https://github.com/castorini/anserini/blob/neuclir22-splade/docs/regressions-neuclir22-fa-qt-splade.md#effectiveness

Interesting that PRF _decreases_ effectiveness.

**Comment by cadurosar** [comment]
> @cadurosar Q for you - what do you want to call the SPLADE model?

Not sure, maybe splade-neuclir22-fa? It is not exactly the same we would use on other data 
 
> In terms of initial sanity checking... do the numbers look right to you?

They are in the same ballpark, but not exactly the same as the last ones I've received from the organizers. I still have to test them locally, but to be sure, here you are using which queries? Human translated or query translated?

**Comment by lintool** [comment]
@cadurosar when you get a chance, please sanity check the QT SPLADE modes:

+ fa: https://github.com/castorini/anserini/blob/neuclir22-splade/docs/regressions-neuclir22-fa-qt-splade.md
+ ru: https://github.com/castorini/anserini/blob/neuclir22-splade/docs/regressions-neuclir22-ru-qt-splade.md
+ zh: https://github.com/castorini/anserini/blob/neuclir22-splade/docs/regressions-neuclir22-zh-qt-splade.md

**Comment by cadurosar** [comment]
> @cadurosar when you get a chance, please sanity check the QT SPLADE modes:
> 
> * fa: https://github.com/castorini/anserini/blob/neuclir22-splade/docs/regressions-neuclir22-fa-qt-splade.md
> * ru: https://github.com/castorini/anserini/blob/neuclir22-splade/docs/regressions-neuclir22-ru-qt-splade.md
> * zh: https://github.com/castorini/anserini/blob/neuclir22-splade/docs/regressions-neuclir22-zh-qt-splade.md

LGTM

**Comment by lintool** [comment]
@cadurosar the DT SPLADE models, in readable doc form:

+ https://github.com/castorini/anserini/blob/neuclir22-splade/docs/regressions-neuclir22-fa-dt-splade.md
+ https://github.com/castorini/anserini/blob/neuclir22-splade/docs/regressions-neuclir22-ru-dt-splade.md
+ https://github.com/castorini/anserini/blob/neuclir22-splade/docs/regressions-neuclir22-ru-dt-splade.md

**Comment by cadurosar** [comment]
Results match what I have here, so looks good to me.

One suggestion for the text is adding naver/splade-cocondenser-selfdistil to SPLADE, like SPLADE ([naver/splade-cocondenser-selfdistil](https://huggingface.co/naver/splade-cocondenser-selfdistil)) to mark which version it is (hope to be able to do the same for the others)

**Comment by lintool** [comment]
> One suggestion for the text is adding naver/splade-cocondenser-selfdistil to SPLADE, like SPLADE ([naver/splade-cocondenser-selfdistil](https://huggingface.co/naver/splade-cocondenser-selfdistil)) to mark which version it is (hope to be able to do the same for the others)

Will do - in my next iteration I'll tweak the documentation.

**Comment by lintool** [comment]
@cadurosar this is ready for your review.

You had a comment above on what to call the models. Settled on:

+ QT: just called it "SPLADE NeuCLIR22" - https://github.com/castorini/anserini/blob/neuclir22-splade/docs/regressions-neuclir22-fa-qt-splade.md
+ DT: [SPLADE CoCondenser SelfDistil](https://huggingface.co/naver/splade-cocondenser-selfdistil) - https://github.com/castorini/anserini/blob/neuclir22-splade/docs/regressions-neuclir22-fa-dt-splade.md

**Review by cadurosar — APPROVED** [review]
LGTM, checked text and hash for Persian + results match what I expected

**Pull request merged**
