### PR TITLE
chore(doc): add a reporduction entry in star-here.md

### PR DESCRIPTION
**Pull request by alirezaJvh**
I can not run it on a Mac M3; however, it works properly on Linux with an Intel CPU.

### CODE REVIEW

**Comment by lintool** [comment]
Hi @alirezaJvh can you explain what didn't work on M3? Should work...

**Comment by lintool** [comment]
Hi @alirezaJvh - please resolve conflicts?

**Comment by alirezaJvh** [comment]
Hi @lintool .sorry for delay response. I was in travel. I'll check it again and tell you what was the issue.

**Comment by lintool** [comment]
Closing, having seen no follow up.

**Pull request closed without merging**
