### PR TITLE
Fixed #375

### LINKED ISSUE #375: WashingPostCollection does not work properly
When I run to index the WashingtonPost collection v2: `~/Anserini/target/appassembler/bin/IndexCollection -collection WashingtonPostCollection -input /scratch2/more_collections/WashingtonPost.v2/WashingtonPost.v2/data/ -generator JsoupGenerator -index lucene-index.wash18.pos+docvectors -threads 44 -storePositions -storeDocvectors -optimize &>log.wash18.pos+docvectors`

The error occurs:
```
java.lang.NullPointerException
        at io.anserini.index.IndexCollection$IndexerThread.run(IndexCollection.java:198) [anserini-0.1.1-SNAPSHOT.jar:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_181]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_181]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_181]
2018-08-02 10:24:33,729 WARN  [main] index.IndexCollection (IndexCollection.java:365) - Unexpected difference between number of indexed documents and index maxDoc.
2018-08-02 10:24:33,730 INFO  [main] index.IndexCollection (IndexCollection.java:368) - # Final Counter Values
2018-08-02 10:24:33,730 INFO  [main] index.IndexCollection (IndexCollection.java:369) - indexed:                0
2018-08-02 10:24:33,730 INFO  [main] index.IndexCollection (IndexCollection.java:370) - empty:                 84
2018-08-02 10:24:33,730 INFO  [main] index.IndexCollection (IndexCollection.java:371) - unindexed:             84
2018-08-02 10:24:33,730 INFO  [main] index.IndexCollection (IndexCollection.java:372) - unindexable:            0
2018-08-02 10:24:33,731 INFO  [main] index.IndexCollection (IndexCollection.java:373) - skipped:                3
2018-08-02 10:24:33,731 INFO  [main] index.IndexCollection (IndexCollection.java:374) - errors:                 0
2018-08-02 10:24:33,736 INFO  [main] index.IndexCollection (IndexCollection.java:377) - Total 30,745 documents indexed in 00:00:24
```
And the indexer quits unexpectedly

### PR DESCRIPTION
**Pull request by Kytabyte**
I addressed a dirty way to solve this problem as I'm not familiar with Jackson library and we have to get Wapo indexing now.

### CODE REVIEW

**Comment by borislin** [comment]
@Kytabyte Remove this [line?](https://github.com/castorini/Anserini/blob/8de9fc046fcb188957c171190be927a2317d5430/src/main/java/io/anserini/collection/WashingtonPostCollection.java#L172) It's redundant.

**Comment by Kytabyte** [comment]
@borislin This is a Document field storing the document content string [here](https://github.com/castorini/Anserini/blob/8de9fc046fcb188957c171190be927a2317d5430/src/main/java/io/anserini/collection/WashingtonPostCollection.java#L129)

**Comment by Kytabyte** [comment]
I came across a new bug while searching the collection with the index. Please leave this PR until I addressed this issue.

**Comment by borislin** [comment]
@Kytabyte No, the field you are referring to is [this](https://github.com/castorini/Anserini/blob/8de9fc046fcb188957c171190be927a2317d5430/src/main/java/io/anserini/collection/WashingtonPostCollection.java#L144).

**Comment by Kytabyte** [comment]
@borislin I see! Addressed!

**Comment by lintool** [comment]
@borislin can you do CR here? Let’s fix it correctly... no jank please...

**Comment by borislin** [comment]
@Kytabyte Are `List<String>` and 'Map<String, String>' new types for `content` in wapo v2? When I did the Jackson refactor, I don't think the [original design](https://github.com/castorini/Anserini/pull/322/files#diff-e476518a5bd6aba9a04055bc1d84e7abL81) supports these two types.

**Comment by Kytabyte** [comment]
@borislin No, it's not a new feature. Actually, there is` List<String>` and `Map<String, String>` in original wapo collection but I didn't notice that because there may be only, say one or two paragraphs out of 10 documents have these structures. However, the JSON parser I used to use is not a recursive parser, so these `List`s or `Map`s are treated as `String` so no errors raised.  So when Jackson recursively parse these files, the types are getting mismatched.

**Comment by borislin** [comment]
@Kytabyte I see. Can you add a custom deserializer for the `Content` class instead of using `Object` in a janky way?

Examples:

http://www.baeldung.com/jackson-deserialization

https://github.com/castorini/Anserini/blob/master/src/main/java/io/anserini/ltr/feature/OrderedQueryPairsFeatureExtractor.java#L35

**Comment by Kytabyte** [comment]
@borislin Sure. Will do!

**Comment by Kytabyte** [comment]
@borislin addressed CR!

**Comment by Peilin-Yang** [comment]
@Kytabyte Did you test the PR against the v2 corpus?

**Comment by Kytabyte** [comment]
@Peilin-Yang Yes. The number of indexed files/empty files is the same as the one from my original design now.

**Pull request merged**
