### PR TITLE
MS MARCO documents on ElasticSearch

### PR DESCRIPTION
**Pull request by HangCui0510**

### CODE REVIEW

**Comment by HangCui0510** [comment]
@eiston , Can you please check if it compiles fine now?

**Comment by HangCui0510** [comment]
Screen Shot 2020-05-05 at 2 56 19 PM

**Comment by lintool** [comment]
@HangCui0510 for next time, instead of starting a new PR each time, can you learn how to update an existing PR? Thanks!

**Comment by eiston** [comment]
> @eiston , Can you please check if it compiles fine now?

It compiled fine, and I think it works now
Screenshot from 2020-05-05 15-30-07

**Comment by HangCui0510** [comment]
@lintool Yes, I will update the same PR in the future.

**Pull request merged**
