### PR TITLE
replicaion on core17/18/robust04

### PR DESCRIPTION
**Pull request by yuki617**
Environment:
    macOS Catalina/ Ubuntu Virtual Machine
    Java 11.0.7
    Python 3.8

### CODE REVIEW

**Comment by lintool** [comment]
hi @yuki617 these entries go in https://github.com/castorini/anserini/tree/master/src/main/resources/docgen/templates

The docs in `docs/` are auto-gen'ed as part of the build/test cycle.

**Comment by yuki617** [comment]
Oops,my bad. Just updated it.

**Comment by lintool** [comment]
run `mvn clean package appassembler:assemble` and it should autogen the md files in `docs/` - check those in also please.

**Comment by yuki617** [comment]
Done

**Pull request merged**
