### PR TITLE
---Do not merge --- Add es end to end test

### PR DESCRIPTION
**Pull request by yxzhu16**
Followed mainly on these two tutorials to create the test, as there weren't much offical documentations on ES Integration tests:
https://www.hascode.com/2016/08/elasticsearch-integration-testing-with-java/
https://github.com/joel-costigliola/elastic-search-test/blob/master/src/test/java/es/example/test/integration/EsIntegrationTest.java

There's no compilation errors, but when I run the maven build, the following exception was raised: 
```
java.lang.NoClassDefFoundError: org/elasticsearch/SecureSM
	at org.elasticsearch.test.ESTestCase.<clinit>(ESTestCase.java:175)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:398)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$2.run(RandomizedRunner.java:623)
Caused by: java.lang.ClassNotFoundException: org.elasticsearch.SecureSM
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	... 4 more
```

followed by:

```
Exception in thread "Thread-18" java.lang.NoClassDefFoundError: Could not initialize class org.elasticsearch.test.ESTestCase
	at java.base/java.lang.Thread.run(Thread.java:834)
	Suppressed: java.lang.IllegalStateException: No context information for thread: Thread[id=107, name=Thread-18, state=RUNNABLE, group=TGRP-ESEndToEndTest]. Is this thread running under a class com.carrotsearch.randomizedtesting.RandomizedRunner runner context? Add @RunWith(class com.carrotsearch.randomizedtesting.RandomizedRunner.class) to your test class. Make sure your code accesses random contexts within @BeforeClass and @AfterClass boundary (for example, static test class initializers are not permitted to access random contexts).
		at com.carrotsearch.randomizedtesting.RandomizedContext.context(RandomizedContext.java:249)
		at com.carrotsearch.randomizedtesting.RandomizedContext.current(RandomizedContext.java:134)
		at com.carrotsearch.randomizedtesting.RandomizedRunner.augmentStackTrace(RandomizedRunner.java:1885)
		at com.carrotsearch.randomizedtesting.RunnerThreadGroup.uncaughtException(RunnerThreadGroup.java:20)
		at java.base/java.lang.Thread.dispatchUncaughtException(Thread.java:2001)

```

It seems like it's complaining about I didn't use `com.carrotsearch.randomizedtesting.RandomizedRunner.class`, even though I've already added it at line 31. 
I've done much investigations regarding this issue, and the closest I've found is this one:
https://discuss.elastic.co/t/could-not-initialize-class-org-elasticsearch-test-estestcase-alternate-solution/117641
He is using `Gradle`, and I tried what he has done in `maven` by excluding `hamcrest ` and `hamcrest -core` in `pom.xml`, there's no luck. 
Would be great if someone more proficient in ES and maven can take a look.  Thanks.

### CODE REVIEW

**Comment by lintool** [comment]
@jpountz can you provide some pointers?

**Comment by jpountz** [comment]
There is indeed a JAR hell issue, hamcrest-all vs. hamcrest-core is one, but I tried to fix it and just got another one. To me the problem is that tests are putting everything an the classpath: Lucene, Solr, Elasticsearch and more. And Elasticsearch's test framework is picky that classes exist in a single JAR. This is important to make sure that behavior in tests will be the same in production, otherwise you could end up loading a given class in tests and another one in production.

In my opinion the best way forward would be to have the ES tests in a dedicated Maven (sub) project where only Elasticsearch and Anserini-related classes are on the classpath.

**Comment by lintool** [comment]
@jpountz Thanks for the help!

> In my opinion the best way forward would be to have the ES tests in a dedicated Maven (sub) project where only Elasticsearch and Anserini-related classes are on the classpath.

I see - is this what ES does internally?

**Comment by jpountz** [comment]
It is a mix of this and excluding optional dependencies we don't need indeed.

**Comment by lintool** [comment]
Seems like this isn't particular worthwhile, so closing...

**Pull request closed without merging**
