### PR TITLE
BM25 Baselines for MS MARCO Passage Ranking in Anserini + MS MARCO Evaluation, TREC Evaluation

### PR DESCRIPTION
**Pull request by Linsen-gao-457**
Begin your journey（Forrest）and Anserini: BM25 Baselines for MS MARCO Passage Ranking（Forrest）

First project:
ECEUbnuntu (limitted storage)
Operating System: Ubuntu 20.04.6 LTS
Kernel Version: 5.15.0-122-generic
Python Version:** 3.8.10
Maven Version: Apache Maven 3.8.1
Memory: 125 GiB
Processor: AMD Ryzen 9 5900X 12-Core Processor (12 cores, 24 threads, Base 3.7 GHz, Boost 4.3 GHz)
Outcome: All steps completed successfully

Second project:
My computer
Operating System: Windows 10 Home Chinese Version
Version: 22H2
Installation Date: January 19, 2022
Build Version: 19045.5247
Processor: AMD Ryzen 7 4800H with Radeon Graphics (Base 2.90 GHz)
Memory: 16 GB (15.4 GB usable)
System Type: 64-bit Operating System, x64-based Processor
Outcome: All steps completed successfully
Issues Encountered:
Windows Virtual Memory Allocation Issue:
High memory usage during inverted index construction caused system memory exhaustion.
Solution: Manually increased Windows virtual memory allocation to approximately 200 GB to ensure the indexing process completed smoothly.
TREC Tool Incompatibility on Windows: The default trec_eval tool does not support native Windows execution.
Solution: Recompiled trec_eval using MSYS2 to successfully execute the tool
High memory usage during inverted index construction caused system memory exhaustion.
Solution: Manually increased Windows virtual memory allocation to approximately 200 GB to ensure the indexing process completed smoothly.
TREC Tool Incompatibility on Windows: The default trec_eval tool does not support native Windows execution.
Solution: Recompiled trec_eval using MSYS2 to successfully execute the tool

### CODE REVIEW

**Comment by lintool** [comment]
Please revert changes to all files except for the onboarding docs.

**Comment by lintool** [comment]
@Linsen-gao-457 please fix conflicts?

**Comment by Linsen-gao-457** [comment]
> Linsen



> @Linsen-gao-457 please fix conflicts?

Finish! If there is any problem, plz let me know

**Comment by lintool** [comment]
This should _not_ be the case:

Screen Shot 2024-12-25 at 5 05 44 PM

The only files that should have changed are the two `.md` files as part of the onboarding path.

**Comment by Linsen-gao-457** [comment]
> This should _not_ be the case:
> 
> Screen Shot 2024-12-25 at 5 05 44 PM
> The only files that should have changed are the two `.md` files as part of the onboarding path.

Oh, sorry! I have already merge the new branch. So should i cancel this pull request now?

But i find there are some mistaken format in the md file. like Results reproduced by [@Linsen-gao-457](https://github.com/Linsen-gao-457) on 2024-12-16 (commit ['a86484a'] instead of Results reproduced by [@Linsen-gao-457](https://github.com/Linsen-gao-457) on 2024-12-16 (commit [a86484a6](https://github.com/castorini/anserini/commit/a86484a6e99a7a97966c423d230ad05279b24508))

This branch has already merged. should i raise another pull request?

**Comment by lintool** [comment]
My mistake, this PR is defunct; https://github.com/castorini/anserini/pull/2664 has already been merged.

**Comment by Linsen-gao-457** [comment]
> My mistake, this PR is defunct; #2664 has already been merged.



> My mistake, this PR is defunct; #2664 has already been merged.

No problem. And more important: Merry Chrismas!

**Pull request closed without merging**
