### PR TITLE
Manually construct query instead of using QueryParser.

### PR DESCRIPTION
**Pull request by r-clancy**
@lintool I suspect the same issue with the tests as the Rm3 change (`cw09b` is failing) - I'll re-run the failed regressions once they've finished with more logging and update the regression results if that's the issue.

### CODE REVIEW

**Comment by r-clancy** [comment]
@lintool The issue here was related to #452 - the query "403b" didn't have any similar terms in the query expansion. Previously the original query was fed into the query parser when this happened, so I've updated the code here to just do a TermQuery (instead of BoostQuery) when no similar terms are found.

The failing regression looks to be passing, I'll run the others over the next day for a sanity check.

**Comment by Peilin-Yang** [comment]
Are the regression tests all passed?

**Comment by r-clancy** [comment]
@Peilin-Yang cw09b was the only failing test, it looks to be good now. I'm running the others just to make sure the change didn't effect them.

**Comment by lintool** [comment]
@r-clancy Did the regression numbers change for cw09b? I don't see a diff of AP here in this PR.

**Comment by lintool** [comment]
Okay, thanks - once you confirm the other regressions pass okay, we'll be good to merge.

**Pull request merged**
