### PR TITLE
Possible fix for flaky C4EndToEndTest

### PR DESCRIPTION
**Pull request by lintool**
Test seems to fail sometimes... checking to see if this is a possible fix.

### CODE REVIEW

**Comment by lintool** [comment]
@MXueguang @stephaniewhoo not sure this will fix the flaky test issue, but let's give it a try?

**Comment by MXueguang** [comment]
My Ubuntu 20.0.4 environment 
Tests run: 390, Failures: 0, Errors: 0, Skipped: 0

**Comment by lintool** [comment]
> My Ubuntu 20.0.4 environment
> Tests run: 390, Failures: 0, Errors: 0, Skipped: 0

Yes, it works for me locally too... but CI shows failed tests sometimes... error log has a funky locale set, so I'm suspecting that might be the issue?

**Comment by lintool** [comment]
FWIW, screenshot of failed test -

Screen Shot 2021-04-27 at 8 40 50 PM

Note it says `-Dtests.locale=fa-IR` - huh?

**Comment by MXueguang** [comment]
yeah, so the CI passed this time right?

**Review by MXueguang — APPROVED** [review]

**Pull request merged**
