### PR TITLE
Add CORD-19 Instructions to Elastirini Doc

### PR DESCRIPTION
**Pull request by HangCui0510**

### CODE REVIEW

**Comment by lintool** [comment]
@stephaniewhoo @shaneding can you try these instructions out?

**Comment by stephaniewhoo** [comment]
> @stephaniewhoo @shaneding can you try these instructions out?

not sure if I missed anything on my local machine. 
after `elastirini/bin/kibana`, my terminal keeps telling me
`  log   [01:31:30.122] [warning][data][elasticsearch] Unable to revive connection: http://localhost:9200/
  log   [01:31:30.123] [warning][data][elasticsearch] No living connections
  log   [01:31:30.123] [warning][licensing][plugins] License information could not be obtained from Elasticsearch due to Error: No Living connections error
  log   [01:31:30.315] [warning][admin][elasticsearch] Unable to revive connection: http://localhost:9200/
  log   [01:31:30.316] [warning][admin][elasticsearch] No living connections
  log   [01:31:32.815] [warning][admin][elasticsearch] Unable to revive connection: http://localhost:9200/
  log   [01:31:32.816] [warning][admin][elasticsearch] No living connections
  log   [01:31:35.317] [warning][admin][elasticsearch] Unable to revive connection: http://localhost:9200/
  log   [01:31:35.319] [warning][admin][elasticsearch] No living connections
  log   [01:31:37.819] [warning][admin][elasticsearch] Unable to revive connection: http://localhost:9200/
  log   [01:31:37.819] [warning][admin][elasticsearch] No living connections`

**Comment by HangCui0510** [comment]
@stephaniewhoo I think you need to have elasticsearch running.
Screen Shot 2020-05-25 at 9 38 22 PM

**Comment by stephaniewhoo** [comment]
> @stephaniewhoo I think you need to have elasticsearch running.
> Screen Shot 2020-05-25 at 9 38 22 PM

Thanks, and I have tried those instructions. It worked for me. @lintool

**Comment by lintool** [comment]
Thanks @HangCui0510 for the contribution!

**Comment by shaneding** [comment]
I received the error: 
ERROR [pool-2-thread-1] index.IndexCollection$ESIndexerThread (IndexCollection.java:575) - Error sending bulk requests to Elasticsearch
org.elasticsearch.ElasticsearchStatusException: Unable to parse response body
when trying to index the abstract, body and paragraph, although it didn't seem to stop the indexing.

However, on kibana I can't seem to view any of the docs, and the count aggregate was 0 for me, so I was thinking if there was a loading error or something? Although this could be wrong as I am not very familiar with how kibana works.

**Comment by HangCui0510** [comment]
we need to first load elasticsearch index
Screen Shot 2020-05-26 at 2 22 06 AM
Screen Shot 2020-05-26 at 2 25 00 AM
Screen Shot 2020-05-26 at 2 25 14 AM

For visualization, we need to adjust parameters in "Metrics" and "Buckets" to get desired graphs.
Example:
Screen Shot 2020-05-26 at 2 43 39 AM

**Comment by shaneding** [comment]
I am still getting the same error, and the index is available to me, it just seems like that there is no data associated with it. This might just be an issue for my laptop though, since others were able to replicate it.

**Pull request merged**
