### PR TITLE
add entries in the reproduction logs

### PR DESCRIPTION
**Pull request by AliRanjbari**
Run it on google colab and everything worked!
But I encountered an error while attempting to extract the .tar file on my Linux (Ubuntu) system. The error message displayed was as 

```
.tar.gz -C collections/msmarco-passage
collection.tsv

follows: gzip: stdin: unexpected end of file
tar: Unexpected EOF in archive
tar: Unexpected EOF in archive
tar: Error is not recoverable: exiting now
```

### CODE REVIEW

**Comment by lintool** [comment]
It does not appear that the download completed. Have you checked the checksum?

**Comment by AliRanjbari** [comment]
Oh yes, that was the reason it was attempting to extract the wrong file. I'm not sure why, but it seems there was another file named `collectionandqueries.tar.gz`, and when I downloaded it, the system automatically renamed it to `collectionandqueries.tar.gz.1`

**Comment by AliRanjbari** [comment]
OK, now I done it on my system. Everything worked!

**Comment by lintool** [comment]
Please describe your system: OS, versions of different packages, etc.

**Comment by AliRanjbari** [comment]
1. OS: Linux (Ubuntu 22.04)
2. Development environment: Python 3.10.12, Java 11.0.20.1
3. Hardware: 16 gig RAM, i5 11gen cpu, RTX3050 gpu

**Comment by lintool** [comment]
Please continue along the onboarding path until you reach the end of the exercises, and then we'll take a look all at once.

**Comment by AliRanjbari** [comment]
I have removed the previous pull request and integrated all the commits into this one

**Review by lintool — APPROVED** [review]

**Pull request merged**
