### PR TITLE
Added more intro material in MS MARCO passage replication guide

### PR DESCRIPTION
**Pull request by lintool**
Recent students who have done this replication, I'd appreciate your comments: what isn't clear?

cc @ArthurChen189 @printfCalvin @saileshnankani @andrewyguo

### CODE REVIEW

**Comment by ArthurChen189** [comment]
Looks clear to me!

**Comment by saileshnankani** [comment]
Looks clear to me as well. The details are really helpful!

**Review by MXueguang — APPROVED** [review]
LGTM

**Comment by printfCalvin** [comment]
I think newly added details really help when recreating this experiment.

**Pull request merged**
