### PR TITLE
Added score tie-breaking to BM25PrfReranker

### LINKED ISSUE #774: MS MARCO passage regression errors: BM25prf gives non-deterministic results
Hi @emmileaf I'm getting these MS MARCO passage regression errors:

This is on `tuna`:

```
2019-08-11 03:55:02,107 - regression_test - ERROR - !!!!!{"actual": 0.1518, "collection": "msmarco-passage", "expected": 0.152, "metric": "map", "model": "bm25-default+prf", "topic": "[MS MARCO Passage Ranking: Dev Queries](https://github.com/microsoft/MSMARCO-Passage-Ranking)"}!!!!!
...
2019-08-11 03:56:41,141 - regression_test - ERROR - !!!!!{"actual": 0.1579, "collection": "msmarco-passage", "expected": 0.1582, "metric": "map", "model": "bm25-tuned+prf", "topic": "[MS MARCO Passage Ranking: Dev Queries](https://github.com/microsoft/MSMARCO-Passage-Ranking)"}!!!!!
```

This is on another machine:

```
2019-08-11 03:38:45,575 - regression_test - ERROR - !!!!!{"actual": 0.1519, "collection": "msmarco-passage", "expected": 0.152, "metric": "map", "model": "bm25-default+prf", "topic": "[MS MARCO Passage Ranking: Dev Queries](https://github.com/microsoft/MSMARCO-Passage-Ranking)"}!!!!!
...
2019-08-11 03:39:51,630 - regression_test - ERROR - !!!!!{"actual": 0.158, "collection": "msmarco-passage", "expected": 0.1582, "metric": "map", "model": "bm25-tuned+prf", "topic": "[MS MARCO Passage Ranking: Dev Queries](https://github.com/microsoft/MSMARCO-Passage-Ranking)"}!!!!!
```
It seems like BM25prf gives non-deterministic results?

@matthew-z any ideas?

### PR DESCRIPTION
**Pull request by emmileaf**
In this PR:
- Added tie-breaking to second retrieval in `BM25PrfReranker`
- Fixes #774 

@lintool before merging this, could you help with sanity checking on a different machine if it's not too much trouble? I re-ran indexing + retrieval twice on `tuna` to check and there were no changes to the regression numbers, but non-determinism issues might be easier to slip by...

### CODE REVIEW

**Comment by matthew-z** [comment]
I also added that snippet in my local, and the results are now deterministic

**Comment by lintool** [comment]
@emmileaf can you update the regression numbers and I'll also see if they match? Thanks!

**Comment by emmileaf** [comment]
The regression numbers didn't change when I re-ran after the fix, so hopefully it should be able to pass with the current ones?

**Comment by lintool** [comment]
On `tuna`, I'm still getting:

```
2019-08-12 19:27:45,991 - regression_test - INFO - {"actual": 0.1582, "collection": "msmarco-passage", "expected": 0.1582, "metric": "map", "model": "bm25-tuned+prf", "topic": "[MS MARCO Passage Ranking: Dev Queries](https://github.com/microsoft/MSMARCO-Passage-Ranking)"}
```
and

```
2019-08-12 21:51:51,442 - regression_test - ERROR - !!!!!{"actual": 0.1583, "collection": "msmarco-passage", "expected": 0.1582, "metric": "map", "model": "bm25-tuned+prf", "topic": "[MS MARCO Passage Ranking: Dev Queries](https://github.com/microsoft/MSMARCO-Passage-Ranking)"}!!!!!
```

Across two different trials. Untuned BM25 seems to be okay, though. Any ideas?

**Comment by emmileaf** [comment]
I can't seem to reproduce this error on tuna anymore…perhaps try with #776 instead? We both pushed a fix at the same time, but it looks like @matthew-z made a few additional small changes in that PR?

**Comment by lintool** [comment]
I reran a two times on two different machines and am now getting consistent results... I must have been inadvertently running old code? Merging.

**Pull request merged**
