### PR TITLE
tilde unicoil reproduction

### PR DESCRIPTION
**Pull request by MXueguang**
slightly different result:
#####################
MRR @10: 0.34800888024741866
QueriesRanked: 6980
#####################

### CODE REVIEW

**Comment by lintool** [comment]
Do you think this is because of pre-computed queries?

BTW - `topics.msmarco-passage.dev-subset.unicoil-tilde-expansion.tsv.gz`? Change to `unicoil-tilde-expansion` for consistency in naming?

**Comment by lintool** [comment]
hey @MXueguang I'm getting exactly as expected:

```
#####################
MRR @10: 0.34965502342293175
QueriesRanked: 6980
#####################
```

Hrm... wondering what going on?

What OS? I'm on Mac.

Tie-breaking effects?

**Comment by MXueguang** [comment]
Both orca and my Linux machine gives
#####################
MRR @10: 0.34800888024741866
QueriesRanked: 6980
#####################

seems the bm25 scores are different:
```
head runs/run.msmarco-passage-unicoil-tilde-expansion-b8.trec
2 Q0 4339068 1 116185.000000 Anserini
2 Q0 1001873 2 110262.000000 Anserini
2 Q0 6920058 3 107237.000000 Anserini
2 Q0 7496503 4 105887.000000 Anserini
2 Q0 6285817 5 104062.000000 Anserini
2 Q0 3634076 6 103270.000000 Anserini
2 Q0 6285819 7 99772.000000 Anserini
2 Q0 7496505 8 99620.000000 Anserini
2 Q0 4339071 9 97698.000000 Anserini
2 Q0 2022782 10 96587.000000 Anserini
```

**Comment by lintool** [comment]
Hi @MXueguang you are correct. On `damiano`, which is a Linux machine, I get:

```
#####################
MRR @10: 0.34800888024741866
QueriesRanked: 6980
#####################
```

I think we need to sort this out before merging...

**Comment by lintool** [comment]
Hi @MXueguang I was able to reproduce the scores that you're getting - both on Linux and macOS - with your query file.

So the issue is the query file, not the OS. You might be using a different one than @ArvinZhuang sent us? Since we have a new query file, here's what I'm going to do -

1. I'm going to close this issue for now.
2. I'll go over and work on this repro in pyserini, so the otf and pre-computed queries are side by side - easier to compare.
3. After (2) above, it's just a matter of copy and paste over to anserini.

**Pull request closed without merging**
