### PR TITLE
Tweak path to gdeval

### PR DESCRIPTION
**Pull request by lintool**
see #1416 - changes to path need to be propagated to rest of documentation.

### CODE REVIEW

**Review by rodrigonogueira4 — APPROVED** [review]
LGTM, but any reason for changing the topics (51-100 vs 101-150)?

**Comment by lintool** [comment]
I think that's just weirdness in how the diffs are displayed?

**Comment by rodrigonogueira4** [comment]
> I think that's just weirdness in how the diffs are displayed?

Ah, sorry, you are right!

**Review by ronakice — APPROVED** [review]
LGTM!

**Pull request merged**
