### PR TITLE
A script to convert Yahoo Answers collection.

### PR DESCRIPTION
**Pull request by searchivarius**
A couple of notes. 
1. It's not super lightweight, b/c I use numpy. Sorry, I was lazy to reimplement sampling without replacement in Python.
2. The relevance grade is either 4 (for best answers) or 3. I believe this is compatible with the TREC NIST gdeval.pl utility.

### CODE REVIEW

**Comment by searchivarius** [comment]
@Chriskamphuis I will make it compliant.

**Comment by searchivarius** [comment]
Hi @Chriskamphuis I fixed the script, but not types of formatting. Are you sure it's against pep8? pep8 checker doesn't complain about it.

**Comment by Chriskamphuis** [comment]
You're right, that's not PEP8.

**Comment by searchivarius** [comment]
@Chriskamphuis thanks for checking. BTW, what do you use to format according to pep8 standards?

**Comment by Chriskamphuis** [comment]
@searchivarius `flake8` which you can also install as a vim plugin. But for bigger projects I use pycharm, which has pep8 checking build in.

**Pull request closed without merging**
