### PR TITLE
Update Elastirini with MS MARCO Doc

### PR DESCRIPTION
**Pull request by HangCui0510**

### CODE REVIEW

**Comment by lintool** [comment]
@eiston Can you take a quick look to confirm? Thanks in advance!

**Comment by eiston** [comment]
> @eiston Can you take a quick look to confirm? Thanks in advance!
Okay 👌

**Comment by eiston** [comment]
This seems fine, although the output file is inconsistent with [the integration test](https://github.com/castorini/anserini/blob/master/src/main/python/run_es_regression.py) as in the test it is stored in the runs/ folder, however, it is consistent with the rest of the document so I am not sure if it matters. I am currently running indexing to make sure everything is fine. I also noticed the for the msmarco-passage section of this document, for indexing, JsoupGenerator does not exit, changing it to DefaultLuceneDocumentGenerator works.

**Comment by lintool** [comment]
> This seems fine, although the output file is inconsistent with [the integration test](https://github.com/castorini/anserini/blob/master/src/main/python/run_es_regression.py) as in the test it is stored in the runs/ folder, however, it is consistent with the rest of the document so I am not sure if it matters. I am currently running indexing to make sure everything is fine. I also noticed the for the msmarco-passage section of this document, for indexing, JsoupGenerator does not exit, changing it to DefaultLuceneDocumentGenerator works.

Yes, please make the documentation consistent... I don't think anyone has updated these docs in a while (which is precisely why I'm asking for help on these). Yes, please change to `DefaultLuceneDocumentGenerator`.

Update this PR directly with your patch?

**Comment by HangCui0510** [comment]
I have updated the documentation, please review

**Comment by eiston** [comment]
> I have updated the documentation, please review

Seems fine to me

**Comment by lintool** [comment]
Hrm... I ran this:

```
$ python src/main/python/run_es_regression.py --regression msmarco-doc --input /tuna1/collections/msmarco/doc
...
2020-05-08 14:34:32,376 INFO - [SUCESS] 0.2308 MAP verified as expected!
```

In the end I got .2308 MAP, but that doesn't actually match the .2310 MAP reported here: https://github.com/castorini/anserini/blob/master/docs/regressions-msmarco-doc.md

I'll merge this for now and file a new issue.

**Pull request merged**
