### PR TITLE
Add to onboarding reproduction logs

### PR DESCRIPTION
**Pull request by shayanbali**
### setup:

- Operating System: macOS Ventura Version 13.5
- Chip: Apple M2 Pro
- Memory: 16 GB
- Environment: Mac Terminal
- Python: 3.9.6

### status:
everything worked

### CODE REVIEW

**Review by shayanbali — COMMENTED** [review]
There is a typo mistake in Indexing section (effcient -> efficient).

Providing a detailed example of MRR@10 in this document could be helpful for better understanding

**Comment by lintool** [comment]
Thanks for catching the typo!

> Providing a detailed example of MRR@10 in this document could be helpful for better understanding.

What exactly do you mean? MRR is explained here, right? https://github.com/castorini/anserini/blob/master/docs/experiments-msmarco-passage.md#evaluation

Do you have any suggestions for how to improve?

**Review by lintool — APPROVED** [review]

**Comment by shayanbali** [comment]
An example like this can help better understanding:

Scenario:

Imagine we have a search engine that retrieves web pages based on user queries. We want to evaluate the performance of this search engine using MRR@10.

Steps:

### **Generate Sample Queries:**

Let's say we have a set of queries that users might input into the search engine. For instance:

Query 1: "How to bake a cake"
Query 2: "Best hiking trails near me"
Query 3: "Python programming tutorials"
### **Run Queries and Retrieve Results:**

We run these queries through our search engine, and it returns a ranked list of results for each query. For simplicity, let's assume each query returns 10 results.

For Query 1, the top 10 results might be:

Recipe website with detailed instructions on baking a cake (Relevant)
Online store selling cake decorations (Irrelevant)
Blog post about cake decorating techniques (Irrelevant)
...
Cooking forum discussing various recipes (Irrelevant)
Similarly, we have ranked lists for Query 2 and Query 3.

### **Determine Relevance:**

For each query, we manually assess the relevance of the top result. Let's assume:

For Query 1, the most relevant result is at position 1 (as it directly answers the query).
For Query 2, the most relevant result is at position 5 (as it provides information about local hiking trails).
For Query 3, the most relevant result is at position 3 (as it's a high-quality Python programming tutorial).
### **Calculate MRR@10:**

Using the relevance positions we determined, we calculate the Mean Reciprocal Rank at 10:

MRR@10 = (1/1 + 1/5 + 1/3) / 3 ≈ 0.54

**Comment by lintool** [comment]
Hi @shayanbali thanks for the suggestion, but IMO this would be over-explaining and breaking the flow of the current narrative.

**Pull request merged**
