### PR TITLE
Add SimpleIndexer

### PR DESCRIPTION
**Pull request by lintool**
Goal is to enable indexing from the Python end without first having to write out a file.

Initial impl, which is quite simple, uses only a single thread. This will be too painful for indexing even moderate size collections.

### CODE REVIEW

**Comment by lintool** [comment]
Initial implementation done. Some quick performance comparisons:

Normal indexer, running on 9 threads:

```
target/appassembler/bin/IndexCollection \
  -collection JsonCollection \
  -input /System/Volumes/Data/store/collections/msmarco/passage \
  -index indexes/lucene-index.msmarco-passage/ \
  -generator DefaultLuceneDocumentGenerator \
  -threads 9 -storePositions -storeDocvectors -storeRaw

# Total 8,841,823 documents indexed in 00:01:46
```

`SimpleIndexer`, running on a single thread:

```
mvn compile exec:java -Dexec.mainClass="io.anserini.index.SimpleIndexer" \
  -Dexec.args="-input /System/Volumes/Data/store/collections/msmarco/passage -index indexes/lucene-index.msmarco-passage"

# Total 8,841,823 documents indexed in 00:18:08
```

Retrieval runs:

```
target/appassembler/bin/SearchCollection \
  -index indexes/lucene-index.msmarco-passage/ \
  -topics src/main/resources/topics-and-qrels/topics.msmarco-passage.dev-subset.txt \
  -topicreader TsvInt \
  -output runs/run.msmarco-passage.bm25-default.topics.msmarco-passage.dev-subset.txt \
  -bm25

tools/eval/trec_eval.9.0.4/trec_eval -c -m map src/main/resources/topics-and-qrels/qrels.msmarco-passage.dev-subset.txt runs/run.msmarco-passage.bm25-default.topics.msmarco-passage.dev-subset.txt
tools/eval/trec_eval.9.0.4/trec_eval -c -M 10 -m recip_rank src/main/resources/topics-and-qrels/qrels.msmarco-passage.dev-subset.txt runs/run.msmarco-passage.bm25-default.topics.msmarco-passage.dev-subset.txt
tools/eval/trec_eval.9.0.4/trec_eval -c -m recall.100 src/main/resources/topics-and-qrels/qrels.msmarco-passage.dev-subset.txt runs/run.msmarco-passage.bm25-default.topics.msmarco-passage.dev-subset.txt
tools/eval/trec_eval.9.0.4/trec_eval -c -m recall.1000 src/main/resources/topics-and-qrels/qrels.msmarco-passage.dev-subset.txt runs/run.msmarco-passage.bm25-default.topics.msmarco-passage.dev-subset.txt

map                   	all	0.1926
recip_rank            	all	0.1840
recall_100            	all	0.6578
recall_1000           	all	0.8526
```

Retrieval effectiveness checks out.

Let's get this merged in, and I'll build some bindings on the Python side. Then I'll circle back and add in multi-threading.

**Review by MXueguang — APPROVED** [review]

**Comment by theyorubayesian** [comment]
@lintool I'd like to extend this SimpleIndexer to take additional arguments e.g. to specify language & what analyzer to use (rather than the Default English Analyzer). It'd improve our use of the Simple Indexer for the ongoing GAIA Search collab

**Comment by lintool** [comment]
@theyorubayesian sure... do you want to open another issue?

**Comment by theyorubayesian** [comment]
Just did: #2060

**Comment by karrtikiyer** [comment]
@lintool : Thanks for this work, is there some example on how to use this SimpleIndexer on Fly in python, any kind of tutorial or readme files?

**Comment by lintool** [comment]
@karrtikiyer unfortunately, no... we have a documentation stub here:
https://github.com/castorini/pyserini/blob/master/docs/usage-index.md#building-a-bm25-index-embeddable-python-implementation

But unfortunately we haven't had time to flesh out yet.

However, all the features are demonstrated in this test case:
https://github.com/castorini/pyserini/blob/master/tests/test_index_otf.py

If you're interested in using this feature, contributions to docs are welcome!

**Comment by karrtikiyer** [comment]
I am trying to reproduce the below directly on the fly without having to
write JSONL files. Would you be able to help me point out the correct test
case which will help me achieve this?
python -m pyserini.encode \
input --corpus /myfolder/myjson.jsonl \
--fields title text \
output --embeddings indexes/faiss.nfcorpus.contriever-msmarco \
--to-faiss \
encoder --encoder facebook/contriever-msmarco \
--device cuda:0 \
--pooling mean \
--fields title text
Thanks and regards,
Karrtik

**Comment by lintool** [comment]
hi @karrtikiyer - you seem to want to do on-the-fly dense vector indexing. We currently don't have that. This PR was for on-the-fly _sparse_ indexing.

**Comment by karrtikiyer** [comment]
Thanks Jimmy, is this on the roadmap? It takes a lot of time to write JSONL
first for large sets of data and then pass it to Pyserini.
Thanks and regards,
Karrtik

**Comment by theyorubayesian** [comment]
Hi @karrtikiyer & @lintool,

We haven't had a lot of requests for OTF dense indexing so this has never come up. Theoretically, to support on-the-fly dense vector indexing, we need to write a similar class to [JsonlCollectionIterator](https://github.com/castorini/pyserini/blob/4f3da10b99341d0bc2729590c23d9f1654d8ee37/pyserini/encode/_base.py#L59C10-L59C10) which would rely on HF datasets used in streaming mode. 

@karrtikiyer If this is something you can take on on your end, I would be happy to provide support.

**Pull request merged**
