### PR TITLE
Replication log for Elastirini MS MARCO

### PR DESCRIPTION
**Pull request by edwinzhng**
Title

### CODE REVIEW

**Comment by lintool** [comment]
I would prefer a single heading "Replication Log"

And write "Results replicated ... MS MARCO Passage"

**Comment by edwinzhng** [comment]
> I would prefer a single heading "Replication Log"
> 
> And write "Results replicated ... MS MARCO Passage"

updated

**Comment by lintool** [comment]
Sorry to be pedantic, but Replication Logs -> Log (singular)
I'll +1 it now, merge yourself when you've tweaked please.

**Comment by edwinzhng** [comment]
> Sorry to be pedantic, but Replication Logs -> Log (singular)
> I'll +1 it now, merge yourself when you've tweaked please.

Can't merge, I don't have write access

**Pull request merged**
