### PR TITLE
Reading multi-line topic titles from TREC Topic files

### PR DESCRIPTION
**Pull request by alxliu**
Hi @lintool, I'm currently taking Prof. Cormack's IR course.

I was looking into the regressions for Disks 1 & 2, and realized that the current TREC topic reader does not read the topic title if it spans multiple lines (see the test case I updated).

The effectiveness results will probably have to be updated for all TREC regressions, but I'm just putting up this PR for the fix in the code for the time being.

### CODE REVIEW

**Comment by lintool** [comment]
@alxliu okay thanks - we're in the middle of a release process, so I'm going to hold off merging this until we're done. sg?

**Comment by alxliu** [comment]
Sounds good! No rush.

**Comment by lintool** [comment]
@alxliu any further updates on this?

**Comment by alxliu** [comment]
@lintool sorry, been busy with final projects. I can finish this up after the term is over.

**Comment by lintool** [comment]
@alxliu nudge on this?

**Review by eelstretching — COMMENTED** [review]
Looks like this change solves the issue with titles that take more than one line. There are a number of such titles in the TREC adhoc topics. Seems like the test should be expanded to include more of these (e.g., 139,  142) as well as a few more of the single-liners.

Since there were no other dependencies, I moved this class into the mainline code and re-ran an index of TREC disks 1 and 2 and then re-ran the adhoc queries, which resulted in changes in the scores for the baselines.

**Comment by lintool** [comment]
hi @eelstretching - thanks for looking into this. Would you mind sending a PR w/ updated replication numbers and improved test cases?

**Comment by eelstretching** [comment]
I'm happy to do it. I presume you would like me to do it on the main branch, rather than over here?

**Comment by lintool** [comment]
Yes please!

**Comment by lintool** [comment]
Closed by #1482

**Pull request closed without merging**
