### PR TITLE
Add splade-pp-ed beir regression files

### PR DESCRIPTION
**Pull request by justram**
- added yaml/template/docs
- modified README.md
- tested with the collection at `/mnt/users/j587yang/collections/beir-v1.0.0`
- related [PR](https://github.com/castorini/anserini-tools/pull/60)

### CODE REVIEW

**Comment by lintool** [comment]
This is what we have right now:

```bash
% ls src/main/resources/regression/msmarco-* | grep splade
src/main/resources/regression/msmarco-passage-distill-splade-max.yaml
src/main/resources/regression/msmarco-passage-splade-distil-cocodenser-medium.yaml
src/main/resources/regression/msmarco-passage-splade-pp-ed-onnx.yaml
src/main/resources/regression/msmarco-passage-splade-pp-ed.yaml
src/main/resources/regression/msmarco-passage-splade-pp-sd-onnx.yaml
src/main/resources/regression/msmarco-passage-splade-pp-sd.yaml
src/main/resources/regression/msmarco-v2-passage-splade-pp-ed.yaml
src/main/resources/regression/msmarco-v2-passage-splade-pp-sd.yaml
```

Let's be consistent and call it `splade-pp-ed`?

**Comment by justram** [comment]
model renamed

**Review by lintool — APPROVED** [review]

**Comment by lintool** [comment]
Awesome, thanks @justram for this!

Let's get this merged in, and I'll run tests on my end.

**Comment by justram** [comment]
Happy to help! 
Pre-encoded documents can be found in the following directory: `tjena:/mnt/users/j587yang/collections/beir-v1.0.0/splade-pp-ed`. Need to transfer these documents to the respective servers such as orca, tuna, and others before initiating the regression process.

**Comment by lintool** [comment]
> Happy to help! Pre-encoded documents can be found in the following directory: `tjena:/mnt/users/j587yang/collections/beir-v1.0.0/splade-pp-ed`. Need to transfer these documents to the respective servers such as orca, tuna, and others before initiating the regression process.

yup, will do!

**Pull request merged**
