### PR TITLE
Add ONNX model conversion docs

### PR DESCRIPTION
**Pull request by ArthurChen189**
Add MD file for converting and optimizing SPLADE++ from HuggingFace to ONNX

Related to issue #2127

### CODE REVIEW

**Comment by cadurosar** [comment]
Looks good to me, maybe add a test to see if the outputs are close to what is expected? What do you think @lintool ?

**Comment by lintool** [comment]
haha, I usually never say no to unit tests, but this does belong in Anserini... but since the code is in Python, we don't have testing framework set up... so I think good to merge?

**Comment by lintool** [comment]
I think the tests belong on the Pyserini end once we set up the bindings there?

**Comment by cadurosar** [comment]
Yes, I agree is more on the pyserini side, ok seems good to me them.

**Review by cadurosar — APPROVED** [review]

**Pull request merged**
