### PR TITLE
Instructions for indexing COVID collection into Solr

### PR DESCRIPTION
**Pull request by lintool**
@tteofili can you try out these instructions?

### CODE REVIEW

**Comment by lintool** [comment]
I'm going to wait for @tteofili to test drive these instructions prior to merging.

**Comment by lintool** [comment]
Since there's a new data drop of CORD from AI2, I'm going to merge this in so we have the latest instructions.

**Comment by tteofili** [comment]
sorry for the late reply, anyway all is working on good on my side too, so 👍

**Comment by lintool** [comment]
Thanks for trying the instructions out!

**Pull request merged**
