### PR TITLE
Completed start-here - Fatemeh Rashidi

### PR DESCRIPTION
**Pull request by Fatemehrshd**

### CODE REVIEW

**Comment by lintool** [comment]
+ Describe your setup: hardware, OS, etc.
+ Continue along the onboarding path until you reach the end of the exercises, and then we'll take a look all at once.

**Comment by Fatemehrshd** [comment]
I have a Mac M1 with 8G RAM and 256G memory; half of it is empty. In the second part, you mentioned that a machine with > 8 GB RAM is needed. Does this mean that I can't continue this tutorial anymore?

**Comment by Fatemehrshd** [comment]
Sure, thanks.

**Comment by lintool** [comment]
Seeing no follow up, closing.

**Pull request closed without merging**
