### PR TITLE
updated with elastrini and solr replication

### PR DESCRIPTION
**Pull request by jrzhang12**
I could not replicate msmarco doc because there is not enough storage on my laptop

### Env
- os: macos big sur 11.0.1 
- java: 11
- mvn: 3.6.3

### Issue
Solr indexing command not working
After I ran 
```
sh target/appassembler/bin/IndexCollection -collection TrecCollection -generator DefaultLuceneDocumentGenerator \
  -threads 8 -input collections/msmarco-passage/collection_jsonl \
  -solr -solr.index msmarco-passage -solr.zkUrl localhost:9983 \
  -storePositions -storeDocvectors -storeRaw
```
 0 document was indexed 
and here is the log
image

image

the 9 files are thos jsonl converted from tsv

#### Fix
change TrecCollection to JsonCollection

### Result
image

### CODE REVIEW

**Comment by lintool** [comment]
To be clear, you _were_ able to replicate on Elasticsearch?

How are you able to pinpoint the Solr issues to lack of space? Try removing the options `-storePositions -storeDocvectors -storeRaw` - will result in a smaller index.

**Comment by jrzhang12** [comment]
> To be clear, you _were_ able to replicate on Elasticsearch?
> 
> How are you able to pinpoint the Solr issues to lack of space? Try removing the options `-storePositions -storeDocvectors -storeRaw` - will result in a smaller index.

Oh, I could not replicate msmarco **doc** but i replicated  msmarco **passage** on Elasticsearch

However, for Solr, the indexing didnt work. There wasnt any error, but no document was index after i ran that command

**Comment by lintool** [comment]
Hrm. Odd. According to the log, I was able to replicate myself back in Nov 2020. Can you rewind back to my commit point and try again from there?

**Comment by MXueguang** [comment]
@jrzhang12, for msmarco-passage, we need to use `JsonCollection`

try this command:
sh target/appassembler/bin/IndexCollection -collection JsonCollection -generator DefaultLuceneDocumentGenerator \
  -threads 8 -input collections/msmarco-passage/collection_jsonl \
  -solr -solr.index msmarco-passage -solr.zkUrl localhost:9983 \
  -storePositions -storeDocvectors -storeRaw

**Comment by jrzhang12** [comment]
> @jrzhang12, for msmarco-passage, we need to use `JsonCollection`
> 
> try this command:
> 
> ```
> sh target/appassembler/bin/IndexCollection -collection JsonCollection -generator DefaultLuceneDocumentGenerator \
>   -threads 8 -input collections/msmarco-passage/collection_jsonl \
>   -solr -solr.index msmarco-passage -solr.zkUrl localhost:9983 \
>   -storePositions -storeDocvectors -storeRaw
> ```

Thanks! It works

**Review by lintool — APPROVED** [review]

**Pull request merged**
