### PR TITLE
Update acl.md

### PR DESCRIPTION
**Pull request by lintool**
Requirements is actually under `bin/`:
https://github.com/acl-org/acl-anthology/blob/master/bin/requirements.txt

### CODE REVIEW

**Comment by lintool** [comment]
I'm getting this error:

```bash
$ python bin/create_hugo_yaml.py
Traceback (most recent call last):
  File "bin/create_hugo_yaml.py", line 43, in <module>
    from anthology import Anthology
  File "/Users/jimmylin/workspace/acl-anthology/bin/anthology/__init__.py", line 1, in <module>
    from .anthology import Anthology
  File "/Users/jimmylin/workspace/acl-anthology/bin/anthology/anthology.py", line 24, in <module>
    from .formatter import MarkupFormatter
  File "/Users/jimmylin/workspace/acl-anthology/bin/anthology/formatter.py", line 25, in <module>
    from .utils import stringify_children, remove_extra_whitespace
  File "/Users/jimmylin/workspace/acl-anthology/bin/anthology/utils.py", line 28, in <module>
    from .people import PersonName
  File "/Users/jimmylin/workspace/acl-anthology/bin/anthology/people.py", line 18, in <module>
    import anthology.formatter as my_formatter
AttributeError: module 'anthology' has no attribute 'formatter'
```

**Comment by edwinzhng** [comment]
> I'm getting this error:
> 
> ```shell
> $ python bin/create_hugo_yaml.py
> Traceback (most recent call last):
>   File "bin/create_hugo_yaml.py", line 43, in <module>
>     from anthology import Anthology
>   File "/Users/jimmylin/workspace/acl-anthology/bin/anthology/__init__.py", line 1, in <module>
>     from .anthology import Anthology
>   File "/Users/jimmylin/workspace/acl-anthology/bin/anthology/anthology.py", line 24, in <module>
>     from .formatter import MarkupFormatter
>   File "/Users/jimmylin/workspace/acl-anthology/bin/anthology/formatter.py", line 25, in <module>
>     from .utils import stringify_children, remove_extra_whitespace
>   File "/Users/jimmylin/workspace/acl-anthology/bin/anthology/utils.py", line 28, in <module>
>     from .people import PersonName
>   File "/Users/jimmylin/workspace/acl-anthology/bin/anthology/people.py", line 18, in <module>
>     import anthology.formatter as my_formatter
> AttributeError: module 'anthology' has no attribute 'formatter'
> ```

Weird, which Python version?

**Comment by lintool** [comment]
nm, I really need to rtfm.

When you say "(with Python 3.7+)", you really mean it. Above error with Python 3.6.

**Comment by lintool** [comment]
One more thing, it appears I gotta `mkdir build/data` myself?

I believe this is because I didn't run the makefile, and am skipping steps?

Otherwise, if I don't do this `create_hugo_yaml.py` complains about no path.

**Comment by lintool** [comment]
I think I am correct? https://github.com/acl-org/acl-anthology/blob/master/Makefile#L103

**Comment by edwinzhng** [comment]
Yep looks like you are, I must've ran `make` before I ran the script but forgot

**Pull request merged**
